
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/hybrid_mac 

module add_unsigned_24(A, B, Z);
  input [31:0] A, B;
  output [31:0] Z;
  wire [31:0] A, B;
  wire [31:0] Z;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_153, n_154, n_155, n_156, n_157, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_203, n_204, n_205, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_217;
  wire n_218, n_220, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_237, n_238, n_239, n_240, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_309;
  wire n_310, n_311;
  OAI21X1 g968(.A0 (n_101), .A1 (n_222), .B0 (n_140), .Y (n_251));
  OAI21X1 g969(.A0 (n_68), .A1 (n_222), .B0 (n_59), .Y (n_250));
  OAI21X1 g970(.A0 (n_188), .A1 (n_222), .B0 (n_220), .Y (n_249));
  OAI21X1 g971(.A0 (n_187), .A1 (n_222), .B0 (n_232), .Y (n_248));
  OAI21X1 g972(.A0 (n_165), .A1 (n_222), .B0 (n_212), .Y (n_247));
  OAI21X1 g973(.A0 (n_182), .A1 (n_222), .B0 (n_218), .Y (n_246));
  OAI21X1 g974(.A0 (n_184), .A1 (n_222), .B0 (n_221), .Y (n_245));
  OAI21X1 g975(.A0 (n_186), .A1 (n_222), .B0 (n_231), .Y (n_244));
  OAI21X1 g976(.A0 (n_166), .A1 (n_222), .B0 (n_213), .Y (n_243));
  OAI21X1 g977(.A0 (n_157), .A1 (n_222), .B0 (n_199), .Y (n_242));
  OAI21X1 g979(.A0 (n_146), .A1 (n_222), .B0 (n_177), .Y (n_240));
  OAI21X1 g980(.A0 (n_160), .A1 (n_222), .B0 (n_203), .Y (n_239));
  OAI21X1 g981(.A0 (n_185), .A1 (n_222), .B0 (n_225), .Y (n_238));
  OAI21X1 g989(.A0 (n_183), .A1 (n_222), .B0 (n_228), .Y (n_237));
  OAI21X1 g990(.A0 (n_113), .A1 (n_223), .B0 (n_235), .Y (Z[16]));
  NAND2XL g991(.A (n_113), .B (n_223), .Y (n_235));
  AO21X1 g992(.A0 (n_111), .A1 (n_311), .B0 (n_141), .Y (n_234));
  OAI21X1 g993(.A0 (n_74), .A1 (n_207), .B0 (n_84), .Y (n_233));
  AOI21XL g994(.A0 (n_122), .A1 (n_204), .B0 (n_138), .Y (n_232));
  OA21XL g995(.A0 (n_39), .A1 (n_203), .B0 (n_66), .Y (n_231));
  OAI31XL g996(.A0 (n_154), .A1 (n_70), .A2 (n_207), .B0 (n_210), .Y
       (n_230));
  OAI31XL g997(.A0 (n_154), .A1 (n_117), .A2 (n_207), .B0 (n_211), .Y
       (n_229));
  AOI21XL g998(.A0 (n_147), .A1 (n_204), .B0 (n_174), .Y (n_228));
  OAI31XL g999(.A0 (n_154), .A1 (n_149), .A2 (n_207), .B0 (n_198), .Y
       (n_227));
  OAI31XL g1000(.A0 (n_110), .A1 (n_76), .A2 (n_207), .B0 (n_180), .Y
       (n_226));
  AOI21XL g1001(.A0 (n_156), .A1 (n_204), .B0 (n_200), .Y (n_225));
  OAI21X1 g1002(.A0 (n_154), .A1 (n_207), .B0 (n_175), .Y (n_224));
  CLKINVX1 g1003(.A (n_222), .Y (n_223));
  CLKAND2X2 g1004(.A (n_205), .B (n_217), .Y (n_222));
  AOI221X1 g1005(.A0 (n_92), .A1 (n_174), .B0 (n_168), .B1 (n_204), .C0
       (n_143), .Y (n_221));
  AOI21XL g1006(.A0 (n_161), .A1 (n_204), .B0 (n_209), .Y (n_220));
  MXI2XL g1007(.A (n_207), .B (n_311), .S0 (n_124), .Y (Z[8]));
  AOI21XL g1008(.A0 (n_144), .A1 (n_204), .B0 (n_179), .Y (n_218));
  NAND2XL g1009(.A (n_167), .B (n_311), .Y (n_217));
  OAI21XL g1010(.A0 (n_196), .A1 (n_85), .B0 (n_214), .Y (Z[5]));
  OAI21XL g1011(.A0 (n_192), .A1 (n_131), .B0 (n_208), .Y (Z[7]));
  NAND2XL g1013(.A (n_85), .B (n_196), .Y (n_214));
  AOI21X1 g1014(.A0 (n_95), .A1 (n_176), .B0 (n_142), .Y (n_213));
  OA21XL g1015(.A0 (n_65), .A1 (n_177), .B0 (n_37), .Y (n_212));
  AOI2BB1XL g1016(.A0N (n_117), .A1N (n_175), .B0 (n_135), .Y (n_211));
  OA21XL g1017(.A0 (n_70), .A1 (n_175), .B0 (n_64), .Y (n_210));
  OAI21X1 g1018(.A0 (n_58), .A1 (n_173), .B0 (n_50), .Y (n_209));
  NAND2XL g1019(.A (n_131), .B (n_192), .Y (n_208));
  CLKINVX1 g1024(.A (n_311), .Y (n_207));
  AOI211X1 g1026(.A0 (n_99), .A1 (n_135), .B0 (n_137), .C0 (n_197), .Y
       (n_205));
  CLKINVX1 g1027(.A (n_204), .Y (n_203));
  OAI21X1 g1028(.A0 (n_151), .A1 (n_177), .B0 (n_172), .Y (n_204));
  OAI21X1 g1029(.A0 (n_87), .A1 (n_190), .B0 (n_194), .Y (Z[3]));
  XOR2XL g1030(.A (n_90), .B (n_178), .Y (Z[4]));
  OAI211X1 g1031(.A0 (n_150), .A1 (n_173), .B0 (n_34), .C0 (n_162), .Y
       (n_200));
  AOI221X1 g1032(.A0 (n_31), .A1 (n_142), .B0 (n_155), .B1 (n_176), .C0
       (n_52), .Y (n_199));
  AOI211X1 g1033(.A0 (n_56), .A1 (n_135), .B0 (n_44), .C0 (n_193), .Y
       (n_198));
  NOR2XL g1034(.A (n_153), .B (n_175), .Y (n_197));
  NAND2XL g1035(.A (n_40), .B (n_178), .Y (n_196));
  CLKAND2X2 g1037(.A (n_24), .B (n_178), .Y (n_195));
  NAND2XL g1038(.A (n_87), .B (n_190), .Y (n_194));
  NOR2XL g1039(.A (n_149), .B (n_175), .Y (n_193));
  NAND3X1 g1040(.A (n_29), .B (n_24), .C (n_178), .Y (n_192));
  OAI21XL g1041(.A0 (n_170), .A1 (n_89), .B0 (n_189), .Y (Z[2]));
  NAND2BX1 g1042(.AN (n_170), .B (n_71), .Y (n_190));
  NAND2XL g1043(.A (n_170), .B (n_89), .Y (n_189));
  NAND2XL g1044(.A (n_159), .B (n_161), .Y (n_188));
  NAND2XL g1045(.A (n_122), .B (n_159), .Y (n_187));
  NAND2BXL g1046(.AN (n_39), .B (n_159), .Y (n_186));
  NAND2XL g1047(.A (n_159), .B (n_156), .Y (n_185));
  NAND2XL g1048(.A (n_159), .B (n_168), .Y (n_184));
  NAND2XL g1049(.A (n_147), .B (n_159), .Y (n_183));
  NAND2XL g1050(.A (n_144), .B (n_159), .Y (n_182));
  AOI21XL g1052(.A0 (n_75), .A1 (n_141), .B0 (n_78), .Y (n_180));
  OAI2BB1X1 g1053(.A0N (n_49), .A1N (n_138), .B0 (n_60), .Y (n_179));
  NOR2X1 g1058(.A (n_169), .B (n_170), .Y (n_178));
  CLKINVX1 g1059(.A (n_177), .Y (n_176));
  AOI21X1 g1060(.A0 (n_139), .A1 (n_104), .B0 (n_134), .Y (n_177));
  AOI21X1 g1061(.A0 (n_141), .A1 (n_121), .B0 (n_136), .Y (n_175));
  CLKINVX1 g1062(.A (n_174), .Y (n_173));
  OAI211X1 g1063(.A0 (n_60), .A1 (n_38), .B0 (n_42), .C0 (n_164), .Y
       (n_174));
  AOI21X1 g1064(.A0 (n_125), .A1 (n_142), .B0 (n_133), .Y (n_172));
  OAI21X1 g1065(.A0 (n_132), .A1 (n_88), .B0 (n_163), .Y (Z[1]));
  NAND2X1 g1068(.A (n_27), .B (n_132), .Y (n_170));
  NAND2XL g1069(.A (n_26), .B (n_71), .Y (n_169));
  AND2X1 g1070(.A (n_92), .B (n_147), .Y (n_168));
  NOR2XL g1071(.A (n_153), .B (n_154), .Y (n_167));
  NAND2XL g1072(.A (n_95), .B (n_145), .Y (n_166));
  NAND2BXL g1073(.AN (n_65), .B (n_145), .Y (n_165));
  NAND2XL g1074(.A (n_138), .B (n_112), .Y (n_164));
  NAND2XL g1075(.A (n_132), .B (n_88), .Y (n_163));
  NAND2BX1 g1076(.AN (n_82), .B (n_143), .Y (n_162));
  NOR2XL g1077(.A (n_58), .B (n_148), .Y (n_161));
  INVXL g1078(.A (n_159), .Y (n_160));
  NOR2XL g1079(.A (n_151), .B (n_146), .Y (n_159));
  NAND2XL g1083(.A (n_155), .B (n_145), .Y (n_157));
  NOR2XL g1084(.A (n_150), .B (n_148), .Y (n_156));
  AND2X1 g1085(.A (n_31), .B (n_95), .Y (n_155));
  NAND2XL g1086(.A (n_111), .B (n_121), .Y (n_154));
  NAND2XL g1087(.A (n_118), .B (n_99), .Y (n_153));
  NAND2XL g1089(.A (n_95), .B (n_125), .Y (n_151));
  NAND2BX1 g1090(.AN (n_82), .B (n_92), .Y (n_150));
  NAND2XL g1091(.A (n_56), .B (n_118), .Y (n_149));
  CLKINVX1 g1092(.A (n_148), .Y (n_147));
  NAND2XL g1093(.A (n_122), .B (n_112), .Y (n_148));
  CLKINVX1 g1094(.A (n_146), .Y (n_145));
  NAND2XL g1095(.A (n_100), .B (n_104), .Y (n_146));
  AND2X1 g1096(.A (n_49), .B (n_122), .Y (n_144));
  OAI21X1 g1097(.A0 (n_50), .A1 (n_73), .B0 (n_67), .Y (n_143));
  OAI21X1 g1098(.A0 (n_37), .A1 (n_63), .B0 (n_36), .Y (n_142));
  OAI21X1 g1099(.A0 (n_84), .A1 (n_61), .B0 (n_32), .Y (n_141));
  CLKINVX1 g1100(.A (n_139), .Y (n_140));
  OAI21X1 g1101(.A0 (n_59), .A1 (n_81), .B0 (n_33), .Y (n_139));
  OAI21X1 g1102(.A0 (n_66), .A1 (n_83), .B0 (n_57), .Y (n_138));
  OAI21X1 g1103(.A0 (n_45), .A1 (n_77), .B0 (n_62), .Y (n_137));
  OAI21X1 g1104(.A0 (n_79), .A1 (n_72), .B0 (n_47), .Y (n_136));
  OAI21X1 g1105(.A0 (n_64), .A1 (n_51), .B0 (n_46), .Y (n_135));
  OAI21X1 g1106(.A0 (n_35), .A1 (n_54), .B0 (n_69), .Y (n_134));
  OAI21X1 g1107(.A0 (n_53), .A1 (n_80), .B0 (n_28), .Y (n_133));
  CLKINVX1 g1110(.A (n_130), .Y (n_131));
  ADDHX1 g1111(.A (A[7]), .B (B[0]), .CO (n_129), .S (n_130));
  NAND2BX1 g1113(.AN (n_39), .B (n_66), .Y (n_128));
  NAND2BX1 g1115(.AN (n_82), .B (n_34), .Y (n_127));
  NAND2XL g1117(.A (n_53), .B (n_31), .Y (n_126));
  NOR2XL g1118(.A (n_30), .B (n_80), .Y (n_125));
  NOR2BX1 g1119(.AN (n_84), .B (n_74), .Y (n_124));
  NAND2BX1 g1121(.AN (n_63), .B (n_36), .Y (n_123));
  NOR2XL g1122(.A (n_39), .B (n_83), .Y (n_122));
  NOR2XL g1123(.A (n_76), .B (n_72), .Y (n_121));
  NAND2BX1 g1125(.AN (n_65), .B (n_37), .Y (n_120));
  NOR2BX1 g1127(.AN (n_69), .B (n_54), .Y (n_119));
  CLKINVX1 g1128(.A (n_118), .Y (n_117));
  NOR2XL g1129(.A (n_70), .B (n_51), .Y (n_118));
  NAND2BX1 g1131(.AN (n_41), .B (n_35), .Y (n_116));
  NAND2BX1 g1133(.AN (n_81), .B (n_33), .Y (n_115));
  NOR2BX1 g1135(.AN (n_47), .B (n_72), .Y (n_114));
  NAND2BX1 g1136(.AN (n_68), .B (n_59), .Y (n_113));
  NOR2XL g1137(.A (n_48), .B (n_38), .Y (n_112));
  INVXL g1138(.A (n_111), .Y (n_110));
  NOR2XL g1139(.A (n_74), .B (n_61), .Y (n_111));
  NAND2BX1 g1141(.AN (n_58), .B (n_50), .Y (n_109));
  NAND2BX1 g1143(.AN (n_51), .B (n_46), .Y (n_108));
  NAND2XL g1145(.A (n_79), .B (n_75), .Y (n_107));
  NAND2BX1 g1147(.AN (n_70), .B (n_64), .Y (n_106));
  NAND2BX1 g1149(.AN (n_77), .B (n_62), .Y (n_105));
  NOR2XL g1150(.A (n_41), .B (n_54), .Y (n_104));
  NOR2BX1 g1152(.AN (n_67), .B (n_73), .Y (n_103));
  NAND2BX1 g1154(.AN (n_80), .B (n_28), .Y (n_102));
  CLKINVX1 g1155(.A (n_100), .Y (n_101));
  NOR2XL g1156(.A (n_68), .B (n_81), .Y (n_100));
  NOR2XL g1157(.A (n_55), .B (n_77), .Y (n_99));
  NOR2BX1 g1159(.AN (n_42), .B (n_38), .Y (n_98));
  NAND2XL g1161(.A (n_45), .B (n_56), .Y (n_97));
  NAND2XL g1163(.A (n_60), .B (n_49), .Y (n_96));
  NOR2XL g1164(.A (n_65), .B (n_63), .Y (n_95));
  NAND2BX1 g1166(.AN (n_83), .B (n_57), .Y (n_94));
  NAND2BX1 g1168(.AN (n_61), .B (n_32), .Y (n_93));
  NOR2XL g1169(.A (n_58), .B (n_73), .Y (n_92));
  OAI21X1 g1170(.A0 (A[6]), .A1 (B[0]), .B0 (n_29), .Y (n_91));
  OAI21X1 g1171(.A0 (A[4]), .A1 (B[0]), .B0 (n_40), .Y (n_90));
  OAI21X1 g1172(.A0 (A[2]), .A1 (B[0]), .B0 (n_71), .Y (n_89));
  OA21X1 g1173(.A0 (A[1]), .A1 (B[0]), .B0 (n_27), .Y (n_88));
  OAI21X1 g1174(.A0 (A[3]), .A1 (B[0]), .B0 (n_26), .Y (n_87));
  AOI21X1 g1176(.A0 (B[31]), .A1 (A[31]), .B0 (n_43), .Y (n_86));
  OAI21X1 g1177(.A0 (A[5]), .A1 (B[0]), .B0 (n_25), .Y (n_85));
  NAND2XL g1179(.A (B[8]), .B (A[8]), .Y (n_84));
  NOR2XL g1180(.A (B[25]), .B (A[25]), .Y (n_83));
  NOR2XL g1181(.A (B[30]), .B (A[30]), .Y (n_82));
  NOR2XL g1182(.A (B[17]), .B (A[17]), .Y (n_81));
  NOR2XL g1183(.A (B[23]), .B (A[23]), .Y (n_80));
  INVXL g1184(.A (n_79), .Y (n_78));
  NAND2XL g1185(.A (B[10]), .B (A[10]), .Y (n_79));
  NOR2XL g1186(.A (B[15]), .B (A[15]), .Y (n_77));
  CLKINVX1 g1187(.A (n_76), .Y (n_75));
  NOR2XL g1188(.A (B[10]), .B (A[10]), .Y (n_76));
  NOR2XL g1189(.A (B[8]), .B (A[8]), .Y (n_74));
  NOR2XL g1190(.A (B[29]), .B (A[29]), .Y (n_73));
  NOR2XL g1191(.A (B[11]), .B (A[11]), .Y (n_72));
  NAND2XL g1192(.A (A[2]), .B (B[0]), .Y (n_71));
  NOR2XL g1193(.A (B[12]), .B (A[12]), .Y (n_70));
  NAND2XL g1194(.A (B[19]), .B (A[19]), .Y (n_69));
  NOR2XL g1195(.A (B[16]), .B (A[16]), .Y (n_68));
  NAND2XL g1196(.A (B[29]), .B (A[29]), .Y (n_67));
  NAND2XL g1197(.A (B[24]), .B (A[24]), .Y (n_66));
  NOR2XL g1198(.A (B[20]), .B (A[20]), .Y (n_65));
  NAND2XL g1199(.A (B[12]), .B (A[12]), .Y (n_64));
  NOR2XL g1200(.A (B[21]), .B (A[21]), .Y (n_63));
  NAND2XL g1201(.A (B[15]), .B (A[15]), .Y (n_62));
  NOR2XL g1202(.A (B[9]), .B (A[9]), .Y (n_61));
  NAND2XL g1203(.A (B[26]), .B (A[26]), .Y (n_60));
  NAND2XL g1204(.A (B[16]), .B (A[16]), .Y (n_59));
  NOR2XL g1205(.A (B[28]), .B (A[28]), .Y (n_58));
  NAND2XL g1206(.A (B[25]), .B (A[25]), .Y (n_57));
  CLKINVX1 g1207(.A (n_55), .Y (n_56));
  NOR2XL g1208(.A (B[14]), .B (A[14]), .Y (n_55));
  NOR2XL g1209(.A (B[19]), .B (A[19]), .Y (n_54));
  INVXL g1210(.A (n_53), .Y (n_52));
  NAND2XL g1211(.A (B[22]), .B (A[22]), .Y (n_53));
  NOR2XL g1212(.A (B[13]), .B (A[13]), .Y (n_51));
  NAND2XL g1213(.A (B[28]), .B (A[28]), .Y (n_50));
  CLKINVX1 g1214(.A (n_48), .Y (n_49));
  NOR2XL g1215(.A (B[26]), .B (A[26]), .Y (n_48));
  NAND2XL g1216(.A (B[11]), .B (A[11]), .Y (n_47));
  NAND2XL g1217(.A (B[13]), .B (A[13]), .Y (n_46));
  INVXL g1218(.A (n_45), .Y (n_44));
  NAND2XL g1219(.A (B[14]), .B (A[14]), .Y (n_45));
  NOR2XL g1220(.A (B[31]), .B (A[31]), .Y (n_43));
  NAND2XL g1221(.A (B[27]), .B (A[27]), .Y (n_42));
  NOR2XL g1222(.A (B[18]), .B (A[18]), .Y (n_41));
  NAND2XL g1224(.A (A[4]), .B (B[0]), .Y (n_40));
  NOR2XL g1225(.A (B[24]), .B (A[24]), .Y (n_39));
  NOR2XL g1226(.A (B[27]), .B (A[27]), .Y (n_38));
  NAND2XL g1227(.A (B[20]), .B (A[20]), .Y (n_37));
  NAND2XL g1228(.A (B[21]), .B (A[21]), .Y (n_36));
  NAND2XL g1229(.A (B[18]), .B (A[18]), .Y (n_35));
  NAND2XL g1230(.A (B[30]), .B (A[30]), .Y (n_34));
  NAND2XL g1231(.A (B[17]), .B (A[17]), .Y (n_33));
  NAND2XL g1232(.A (B[9]), .B (A[9]), .Y (n_32));
  CLKINVX1 g1233(.A (n_30), .Y (n_31));
  NOR2XL g1234(.A (B[22]), .B (A[22]), .Y (n_30));
  NAND2XL g1235(.A (A[6]), .B (B[0]), .Y (n_29));
  NAND2XL g1236(.A (B[23]), .B (A[23]), .Y (n_28));
  NAND2XL g1237(.A (A[0]), .B (B[0]), .Y (n_132));
  NAND2XL g1238(.A (A[1]), .B (B[0]), .Y (n_27));
  NAND2XL g1239(.A (A[3]), .B (B[0]), .Y (n_26));
  NAND2XL g1240(.A (A[5]), .B (B[0]), .Y (n_25));
  AND2X1 g2(.A (n_40), .B (n_25), .Y (n_24));
  XOR2XL g1242(.A (n_91), .B (n_195), .Y (Z[6]));
  XNOR2XL g1243(.A (n_128), .B (n_239), .Y (Z[24]));
  XNOR2XL g1244(.A (n_127), .B (n_245), .Y (Z[30]));
  XNOR2XL g1245(.A (n_126), .B (n_243), .Y (Z[22]));
  XNOR2XL g1246(.A (n_123), .B (n_247), .Y (Z[21]));
  XNOR2XL g1247(.A (n_120), .B (n_240), .Y (Z[20]));
  XOR2XL g1248(.A (n_119), .B (n_310), .Y (Z[19]));
  XNOR2XL g1249(.A (n_116), .B (n_251), .Y (Z[18]));
  XNOR2XL g1250(.A (n_115), .B (n_250), .Y (Z[17]));
  XOR2XL g1251(.A (n_114), .B (n_226), .Y (Z[11]));
  XNOR2XL g1252(.A (n_109), .B (n_237), .Y (Z[28]));
  XNOR2XL g1253(.A (n_108), .B (n_230), .Y (Z[13]));
  XNOR2XL g1254(.A (n_107), .B (n_234), .Y (Z[10]));
  XNOR2XL g1255(.A (n_106), .B (n_224), .Y (Z[12]));
  XNOR2XL g1256(.A (n_105), .B (n_227), .Y (Z[15]));
  XOR2XL g1257(.A (n_103), .B (n_249), .Y (Z[29]));
  XNOR2XL g1258(.A (n_102), .B (n_242), .Y (Z[23]));
  XOR2XL g1259(.A (n_98), .B (n_246), .Y (Z[27]));
  XNOR2XL g1260(.A (n_97), .B (n_229), .Y (Z[14]));
  XNOR2XL g1261(.A (n_96), .B (n_248), .Y (Z[26]));
  XNOR2XL g1262(.A (n_94), .B (n_244), .Y (Z[25]));
  XNOR2XL g1263(.A (n_93), .B (n_233), .Y (Z[9]));
  XOR2XL g1264(.A (n_86), .B (n_238), .Y (Z[31]));
  XOR2XL g1265(.A (B[0]), .B (A[0]), .Y (Z[0]));
  OAI21X1 g1266(.A0 (n_41), .A1 (n_309), .B0 (n_35), .Y (n_310));
  OA21XL g3(.A0 (n_101), .A1 (n_222), .B0 (n_140), .Y (n_309));
  NAND3BX1 g1267(.AN (n_129), .B (n_29), .C (n_195), .Y (n_311));
endmodule

module accumulator(clk, reset, input_data, accumulated_result);
  input clk, reset;
  input [31:0] input_data;
  output [31:0] accumulated_result;
  wire clk, reset;
  wire [31:0] input_data;
  wire [31:0] accumulated_result;
  wire n_0, n_11, n_22, n_26, n_37, n_48, n_59, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_91;
  add_unsigned_24 add_17_54(.A (accumulated_result), .B
       ({input_data[31:8], 7'b0000000, input_data[0]}), .Z ({n_64,
       n_65, n_66, n_67, n_68, n_70, n_71, n_72, n_73, n_74, n_75,
       n_76, n_77, n_78, n_79, n_81, n_82, n_83, n_84, n_85, n_86,
       n_87, n_88, n_89, n_91, n_11, n_22, n_26, n_37, n_48, n_59,
       n_69}));
  INVXL g3(.A (reset), .Y (n_0));
  DFFRHQX1 \accumulated_result_reg[0] (.RN (n_0), .CK (clk), .D (n_69),
       .Q (accumulated_result[0]));
  DFFRHQX1 \accumulated_result_reg[10] (.RN (n_0), .CK (clk), .D
       (n_87), .Q (accumulated_result[10]));
  DFFRHQX1 \accumulated_result_reg[11] (.RN (n_0), .CK (clk), .D
       (n_86), .Q (accumulated_result[11]));
  DFFRHQX1 \accumulated_result_reg[12] (.RN (n_0), .CK (clk), .D
       (n_85), .Q (accumulated_result[12]));
  DFFRHQX1 \accumulated_result_reg[13] (.RN (n_0), .CK (clk), .D
       (n_84), .Q (accumulated_result[13]));
  DFFRHQX1 \accumulated_result_reg[5] (.RN (n_0), .CK (clk), .D (n_22),
       .Q (accumulated_result[5]));
  DFFRHQX1 \accumulated_result_reg[14] (.RN (n_0), .CK (clk), .D
       (n_83), .Q (accumulated_result[14]));
  DFFRHQX1 \accumulated_result_reg[15] (.RN (n_0), .CK (clk), .D
       (n_82), .Q (accumulated_result[15]));
  DFFRHQX1 \accumulated_result_reg[16] (.RN (n_0), .CK (clk), .D
       (n_81), .Q (accumulated_result[16]));
  DFFRHQX1 \accumulated_result_reg[30] (.RN (n_0), .CK (clk), .D
       (n_65), .Q (accumulated_result[30]));
  DFFRHQX1 \accumulated_result_reg[17] (.RN (n_0), .CK (clk), .D
       (n_79), .Q (accumulated_result[17]));
  DFFRHQX1 \accumulated_result_reg[18] (.RN (n_0), .CK (clk), .D
       (n_78), .Q (accumulated_result[18]));
  DFFRHQX1 \accumulated_result_reg[19] (.RN (n_0), .CK (clk), .D
       (n_77), .Q (accumulated_result[19]));
  DFFRHQX1 \accumulated_result_reg[27] (.RN (n_0), .CK (clk), .D
       (n_68), .Q (accumulated_result[27]));
  DFFRHQX1 \accumulated_result_reg[1] (.RN (n_0), .CK (clk), .D (n_59),
       .Q (accumulated_result[1]));
  DFFRHQX1 \accumulated_result_reg[20] (.RN (n_0), .CK (clk), .D
       (n_76), .Q (accumulated_result[20]));
  DFFRHQX1 \accumulated_result_reg[21] (.RN (n_0), .CK (clk), .D
       (n_75), .Q (accumulated_result[21]));
  DFFRHQX1 \accumulated_result_reg[22] (.RN (n_0), .CK (clk), .D
       (n_74), .Q (accumulated_result[22]));
  DFFRHQX1 \accumulated_result_reg[23] (.RN (n_0), .CK (clk), .D
       (n_73), .Q (accumulated_result[23]));
  DFFRHQX1 \accumulated_result_reg[24] (.RN (n_0), .CK (clk), .D
       (n_72), .Q (accumulated_result[24]));
  DFFRHQX1 \accumulated_result_reg[25] (.RN (n_0), .CK (clk), .D
       (n_71), .Q (accumulated_result[25]));
  DFFRHQX1 \accumulated_result_reg[26] (.RN (n_0), .CK (clk), .D
       (n_70), .Q (accumulated_result[26]));
  DFFRHQX1 \accumulated_result_reg[28] (.RN (n_0), .CK (clk), .D
       (n_67), .Q (accumulated_result[28]));
  DFFRHQX1 \accumulated_result_reg[29] (.RN (n_0), .CK (clk), .D
       (n_66), .Q (accumulated_result[29]));
  DFFRHQX1 \accumulated_result_reg[2] (.RN (n_0), .CK (clk), .D (n_48),
       .Q (accumulated_result[2]));
  DFFRHQX1 \accumulated_result_reg[31] (.RN (n_0), .CK (clk), .D
       (n_64), .Q (accumulated_result[31]));
  DFFRHQX1 \accumulated_result_reg[3] (.RN (n_0), .CK (clk), .D (n_37),
       .Q (accumulated_result[3]));
  DFFRHQX1 \accumulated_result_reg[4] (.RN (n_0), .CK (clk), .D (n_26),
       .Q (accumulated_result[4]));
  DFFRHQX1 \accumulated_result_reg[6] (.RN (n_0), .CK (clk), .D (n_11),
       .Q (accumulated_result[6]));
  DFFRHQX1 \accumulated_result_reg[7] (.RN (n_0), .CK (clk), .D (n_91),
       .Q (accumulated_result[7]));
  DFFRHQX1 \accumulated_result_reg[8] (.RN (n_0), .CK (clk), .D (n_89),
       .Q (accumulated_result[8]));
  DFFRHQX1 \accumulated_result_reg[9] (.RN (n_0), .CK (clk), .D (n_88),
       .Q (accumulated_result[9]));
endmodule

module reduction_unit_with_6_3(A, B, C, D, E, F, G, H, Result);
  input [15:0] A, B, C, D, E, F, G, H;
  output [31:0] Result;
  wire [15:0] A, B, C, D, E, F, G, H;
  wire [31:0] Result;
  assign Result[0] = 1'b0;
  assign Result[1] = 1'b0;
  assign Result[2] = 1'b0;
  assign Result[3] = 1'b0;
  assign Result[4] = 1'b0;
  assign Result[5] = 1'b0;
  assign Result[6] = 1'b0;
  assign Result[7] = 1'b0;
endmodule

module compressor6_3(a, b, c, d, e, f, sum, carry, overflow);
  input a, b, c, d, e, f;
  output sum, carry, overflow;
  wire a, b, c, d, e, f;
  wire sum, carry, overflow;
  wire n_0, n_1, n_2, n_3;
  ADDHXL g62(.A (n_0), .B (n_2), .CO (overflow), .S (carry));
  CLKXOR2X1 g63(.A (n_1), .B (n_3), .Y (sum));
  ADDHXL g64(.A (e), .B (f), .CO (n_2), .S (n_3));
  ADDHXL g65(.A (b), .B (c), .CO (n_0), .S (n_1));
endmodule

module csa_tree_add_85_52_group_59(in_0, in_1, in_2, in_3, in_4, out_0);
  input [2:0] in_0;
  input [15:0] in_1, in_2, in_4;
  input [7:0] in_3;
  output [15:0] out_0;
  wire [2:0] in_0;
  wire [15:0] in_1, in_2, in_4;
  wire [7:0] in_3;
  wire [15:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44;
  assign out_0[0] = 1'b0;
  assign out_0[1] = 1'b0;
  assign out_0[2] = 1'b0;
  assign out_0[3] = 1'b0;
  assign out_0[4] = 1'b0;
  assign out_0[5] = 1'b0;
  assign out_0[6] = 1'b0;
  assign out_0[7] = 1'b0;
  assign out_0[8] = 1'b0;
  assign out_0[9] = 1'b0;
  assign out_0[10] = 1'b0;
  assign out_0[11] = 1'b0;
  assign out_0[12] = 1'b0;
  assign out_0[13] = 1'b0;
  assign out_0[14] = 1'b0;
  NOR2XL g699(.A (n_1), .B (n_44), .Y (out_0[15]));
  AOI32XL g700(.A0 (n_12), .A1 (in_1[11]), .A2 (in_1[12]), .B0 (n_43),
       .B1 (in_1[12]), .Y (n_44));
  OAI21XL g701(.A0 (n_41), .A1 (n_15), .B0 (n_42), .Y (n_43));
  OAI2BB1XL g702(.A0N (n_15), .A1N (n_41), .B0 (n_23), .Y (n_42));
  AOI22XL g703(.A0 (n_40), .A1 (n_25), .B0 (n_39), .B1 (n_24), .Y
       (n_41));
  OR2X1 g704(.A (n_24), .B (n_39), .Y (n_40));
  OAI2BB1XL g705(.A0N (n_26), .A1N (n_37), .B0 (n_38), .Y (n_39));
  OAI211XL g706(.A0 (n_37), .A1 (n_26), .B0 (in_4[8]), .C0 (n_6), .Y
       (n_38));
  OAI2BB1XL g707(.A0N (n_29), .A1N (n_16), .B0 (n_36), .Y (n_37));
  OAI21XL g708(.A0 (n_16), .A1 (n_29), .B0 (n_35), .Y (n_36));
  OAI2BB1XL g709(.A0N (n_30), .A1N (n_33), .B0 (n_34), .Y (n_35));
  OAI21XL g710(.A0 (n_33), .A1 (n_30), .B0 (n_20), .Y (n_34));
  OAI21XL g711(.A0 (n_31), .A1 (n_22), .B0 (n_32), .Y (n_33));
  OAI2BB1XL g712(.A0N (n_22), .A1N (n_31), .B0 (n_27), .Y (n_32));
  AOI32XL g713(.A0 (n_28), .A1 (n_8), .A2 (in_3[4]), .B0 (n_19), .B1
       (n_28), .Y (n_31));
  ADDFX1 g714(.A (in_2[7]), .B (n_3), .CI (in_4[7]), .CO (n_29), .S
       (n_30));
  ADDFX1 g715(.A (n_10), .B (n_7), .CI (in_3[5]), .CO (n_27), .S
       (n_28));
  ADDFX1 g716(.A (in_4[9]), .B (n_5), .CI (n_14), .CO (n_25), .S
       (n_26));
  ADDFX1 g717(.A (n_11), .B (in_4[10]), .CI (n_13), .CO (n_23), .S
       (n_24));
  CLKINVX1 g718(.A (n_21), .Y (n_22));
  ADDFX1 g719(.A (n_4), .B (n_9), .CI (in_3[6]), .CO (n_20), .S (n_21));
  NOR3XL g720(.A (n_18), .B (n_0), .C (n_17), .Y (n_19));
  OAI21XL g721(.A0 (in_3[4]), .A1 (n_8), .B0 (in_3[3]), .Y (n_18));
  AOI222XL g722(.A0 (in_3[0]), .A1 (n_2), .B0 (in_3[1]), .B1 (in_0[1]),
       .C0 (in_0[2]), .C1 (in_3[2]), .Y (n_17));
  CLKXOR2X1 g723(.A (in_4[8]), .B (n_6), .Y (n_16));
  NOR2XL g724(.A (in_1[11]), .B (n_12), .Y (n_15));
  ADDHXL g725(.A (in_1[9]), .B (in_2[9]), .CO (n_13), .S (n_14));
  ADDHXL g726(.A (in_1[10]), .B (in_2[10]), .CO (n_12), .S (n_11));
  ADDHXL g727(.A (in_4[5]), .B (in_2[5]), .CO (n_9), .S (n_10));
  ADDHXL g728(.A (in_4[4]), .B (in_2[4]), .CO (n_7), .S (n_8));
  ADDHXL g729(.A (in_1[8]), .B (in_2[8]), .CO (n_5), .S (n_6));
  ADDHXL g730(.A (in_4[6]), .B (in_2[6]), .CO (n_3), .S (n_4));
  OA21X1 g731(.A0 (in_3[1]), .A1 (in_0[1]), .B0 (in_0[0]), .Y (n_2));
  NAND2XL g732(.A (in_1[14]), .B (in_1[13]), .Y (n_1));
  NOR2XL g733(.A (in_3[2]), .B (in_0[2]), .Y (n_0));
endmodule

module vedic4_4(A, B, result);
  input [3:0] A, B;
  output [7:0] result;
  wire [3:0] A, B;
  wire [7:0] result;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_27, n_28, n_29, n_31, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_42, n_54;
  assign result[7] = 1'b0;
  OAI21XL g848(.A0 (n_38), .A1 (n_29), .B0 (n_42), .Y (result[5]));
  NAND2XL g849(.A (n_29), .B (n_38), .Y (n_42));
  OAI21XL g850(.A0 (n_37), .A1 (n_28), .B0 (n_27), .Y (result[6]));
  OAI21XL g851(.A0 (n_36), .A1 (n_33), .B0 (n_39), .Y (result[4]));
  NAND2XL g852(.A (n_33), .B (n_36), .Y (n_39));
  NAND2XL g853(.A (n_34), .B (n_37), .Y (n_38));
  NAND2XL g854(.A (n_35), .B (n_33), .Y (n_37));
  NAND2XL g855(.A (n_35), .B (n_34), .Y (n_36));
  NAND2BXL g856(.AN (n_31), .B (n_20), .Y (n_35));
  NAND2BXL g857(.AN (n_20), .B (n_31), .Y (n_34));
  ADDFX1 g858(.A (n_23), .B (n_11), .CI (n_24), .CO (n_33), .S
       (result[3]));
  NAND2XL g859(.A (n_18), .B (n_54), .Y (n_31));
  NAND2BXL g861(.AN (n_28), .B (n_27), .Y (n_29));
  NOR2XL g862(.A (n_8), .B (n_25), .Y (n_28));
  NAND2XL g863(.A (n_8), .B (n_25), .Y (n_27));
  AOI21XL g864(.A0 (n_2), .A1 (n_19), .B0 (n_23), .Y (result[2]));
  OAI21XL g865(.A0 (n_17), .A1 (n_16), .B0 (n_10), .Y (n_25));
  OAI21XL g866(.A0 (n_21), .A1 (n_16), .B0 (n_22), .Y (n_24));
  NOR2XL g867(.A (n_2), .B (n_19), .Y (n_23));
  NAND2XL g868(.A (n_16), .B (n_21), .Y (n_22));
  NOR2BXL g869(.AN (n_18), .B (n_17), .Y (n_21));
  NAND3BXL g870(.AN (n_8), .B (B[3]), .C (A[1]), .Y (n_20));
  OAI21XL g871(.A0 (n_14), .A1 (n_9), .B0 (n_16), .Y (n_19));
  NAND2XL g872(.A (n_13), .B (n_15), .Y (n_18));
  NOR2XL g873(.A (n_13), .B (n_15), .Y (n_17));
  NAND2XL g874(.A (n_9), .B (n_14), .Y (n_16));
  NOR2BXL g875(.AN (n_10), .B (n_7), .Y (n_15));
  ADDHXL g876(.A (n_1), .B (n_3), .CO (n_13), .S (n_14));
  NOR2XL g877(.A (n_6), .B (n_9), .Y (result[1]));
  AOI21XL g878(.A0 (n_0), .A1 (n_5), .B0 (n_8), .Y (n_11));
  NAND3XL g879(.A (A[3]), .B (B[1]), .C (n_1), .Y (n_10));
  AND2X1 g880(.A (result[0]), .B (n_3), .Y (n_9));
  NOR2XL g881(.A (n_0), .B (n_5), .Y (n_8));
  AOI22XL g882(.A0 (A[2]), .A1 (B[1]), .B0 (A[3]), .B1 (B[0]), .Y
       (n_7));
  AOI22XL g883(.A0 (A[1]), .A1 (B[0]), .B0 (A[0]), .B1 (B[1]), .Y
       (n_6));
  NAND2XL g884(.A (B[3]), .B (A[0]), .Y (n_5));
  AND2X1 g885(.A (B[0]), .B (A[0]), .Y (result[0]));
  AND2X1 g886(.A (B[1]), .B (A[1]), .Y (n_3));
  NAND2XL g887(.A (B[2]), .B (A[0]), .Y (n_2));
  AND2X1 g888(.A (A[2]), .B (B[0]), .Y (n_1));
  NAND2XL g889(.A (B[2]), .B (A[1]), .Y (n_0));
  NAND3BXL g2(.AN (n_25), .B (A[3]), .C (B[1]), .Y (n_54));
endmodule

module vedic4_4_1(A, B, result);
  input [3:0] A, B;
  output [7:0] result;
  wire [3:0] A, B;
  wire [7:0] result;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_27, n_28, n_29, n_31, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_42, n_54;
  assign result[7] = 1'b0;
  OAI21XL g848(.A0 (n_38), .A1 (n_29), .B0 (n_42), .Y (result[5]));
  NAND2XL g849(.A (n_29), .B (n_38), .Y (n_42));
  OAI21XL g850(.A0 (n_37), .A1 (n_28), .B0 (n_27), .Y (result[6]));
  OAI21XL g851(.A0 (n_36), .A1 (n_33), .B0 (n_39), .Y (result[4]));
  NAND2XL g852(.A (n_33), .B (n_36), .Y (n_39));
  NAND2XL g853(.A (n_34), .B (n_37), .Y (n_38));
  NAND2XL g854(.A (n_35), .B (n_33), .Y (n_37));
  NAND2XL g855(.A (n_35), .B (n_34), .Y (n_36));
  NAND2BXL g856(.AN (n_31), .B (n_20), .Y (n_35));
  NAND2BXL g857(.AN (n_20), .B (n_31), .Y (n_34));
  ADDFX1 g858(.A (n_23), .B (n_11), .CI (n_24), .CO (n_33), .S
       (result[3]));
  NAND2XL g859(.A (n_18), .B (n_54), .Y (n_31));
  NAND2BXL g861(.AN (n_28), .B (n_27), .Y (n_29));
  NOR2XL g862(.A (n_8), .B (n_25), .Y (n_28));
  NAND2XL g863(.A (n_8), .B (n_25), .Y (n_27));
  AOI21XL g864(.A0 (n_2), .A1 (n_19), .B0 (n_23), .Y (result[2]));
  OAI21XL g865(.A0 (n_17), .A1 (n_16), .B0 (n_10), .Y (n_25));
  OAI21XL g866(.A0 (n_21), .A1 (n_16), .B0 (n_22), .Y (n_24));
  NOR2XL g867(.A (n_2), .B (n_19), .Y (n_23));
  NAND2XL g868(.A (n_16), .B (n_21), .Y (n_22));
  NOR2BXL g869(.AN (n_18), .B (n_17), .Y (n_21));
  NAND3BXL g870(.AN (n_8), .B (B[3]), .C (A[1]), .Y (n_20));
  OAI21XL g871(.A0 (n_14), .A1 (n_9), .B0 (n_16), .Y (n_19));
  NAND2XL g872(.A (n_13), .B (n_15), .Y (n_18));
  NOR2XL g873(.A (n_13), .B (n_15), .Y (n_17));
  NAND2XL g874(.A (n_9), .B (n_14), .Y (n_16));
  NOR2BXL g875(.AN (n_10), .B (n_7), .Y (n_15));
  ADDHXL g876(.A (n_1), .B (n_3), .CO (n_13), .S (n_14));
  NOR2XL g877(.A (n_6), .B (n_9), .Y (result[1]));
  AOI21XL g878(.A0 (n_0), .A1 (n_5), .B0 (n_8), .Y (n_11));
  NAND3XL g879(.A (A[3]), .B (B[1]), .C (n_1), .Y (n_10));
  AND2X1 g880(.A (result[0]), .B (n_3), .Y (n_9));
  NOR2XL g881(.A (n_0), .B (n_5), .Y (n_8));
  AOI22XL g882(.A0 (A[2]), .A1 (B[1]), .B0 (A[3]), .B1 (B[0]), .Y
       (n_7));
  AOI22XL g883(.A0 (A[1]), .A1 (B[0]), .B0 (A[0]), .B1 (B[1]), .Y
       (n_6));
  NAND2XL g884(.A (B[3]), .B (A[0]), .Y (n_5));
  AND2X1 g885(.A (B[0]), .B (A[0]), .Y (result[0]));
  AND2X1 g886(.A (B[1]), .B (A[1]), .Y (n_3));
  NAND2XL g887(.A (B[2]), .B (A[0]), .Y (n_2));
  AND2X1 g888(.A (A[2]), .B (B[0]), .Y (n_1));
  NAND2XL g889(.A (B[2]), .B (A[1]), .Y (n_0));
  NAND3BXL g2(.AN (n_25), .B (A[3]), .C (B[1]), .Y (n_54));
endmodule

module vedic4_4_2(A, B, result);
  input [3:0] A, B;
  output [7:0] result;
  wire [3:0] A, B;
  wire [7:0] result;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_27, n_28, n_29, n_31, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_42, n_54;
  assign result[7] = 1'b0;
  OAI21XL g848(.A0 (n_38), .A1 (n_29), .B0 (n_42), .Y (result[5]));
  NAND2XL g849(.A (n_29), .B (n_38), .Y (n_42));
  OAI21XL g850(.A0 (n_37), .A1 (n_28), .B0 (n_27), .Y (result[6]));
  OAI21XL g851(.A0 (n_36), .A1 (n_33), .B0 (n_39), .Y (result[4]));
  NAND2XL g852(.A (n_33), .B (n_36), .Y (n_39));
  NAND2XL g853(.A (n_34), .B (n_37), .Y (n_38));
  NAND2XL g854(.A (n_35), .B (n_33), .Y (n_37));
  NAND2XL g855(.A (n_35), .B (n_34), .Y (n_36));
  NAND2BXL g856(.AN (n_31), .B (n_20), .Y (n_35));
  NAND2BXL g857(.AN (n_20), .B (n_31), .Y (n_34));
  ADDFX1 g858(.A (n_23), .B (n_11), .CI (n_24), .CO (n_33), .S
       (result[3]));
  NAND2XL g859(.A (n_18), .B (n_54), .Y (n_31));
  NAND2BXL g861(.AN (n_28), .B (n_27), .Y (n_29));
  NOR2XL g862(.A (n_8), .B (n_25), .Y (n_28));
  NAND2XL g863(.A (n_8), .B (n_25), .Y (n_27));
  AOI21XL g864(.A0 (n_2), .A1 (n_19), .B0 (n_23), .Y (result[2]));
  OAI21XL g865(.A0 (n_17), .A1 (n_16), .B0 (n_10), .Y (n_25));
  OAI21XL g866(.A0 (n_21), .A1 (n_16), .B0 (n_22), .Y (n_24));
  NOR2XL g867(.A (n_2), .B (n_19), .Y (n_23));
  NAND2XL g868(.A (n_16), .B (n_21), .Y (n_22));
  NOR2BXL g869(.AN (n_18), .B (n_17), .Y (n_21));
  NAND3BXL g870(.AN (n_8), .B (B[3]), .C (A[1]), .Y (n_20));
  OAI21XL g871(.A0 (n_14), .A1 (n_9), .B0 (n_16), .Y (n_19));
  NAND2XL g872(.A (n_13), .B (n_15), .Y (n_18));
  NOR2XL g873(.A (n_13), .B (n_15), .Y (n_17));
  NAND2XL g874(.A (n_9), .B (n_14), .Y (n_16));
  NOR2BXL g875(.AN (n_10), .B (n_7), .Y (n_15));
  ADDHXL g876(.A (n_1), .B (n_3), .CO (n_13), .S (n_14));
  NOR2XL g877(.A (n_6), .B (n_9), .Y (result[1]));
  AOI21XL g878(.A0 (n_0), .A1 (n_5), .B0 (n_8), .Y (n_11));
  NAND3XL g879(.A (A[3]), .B (B[1]), .C (n_1), .Y (n_10));
  AND2X1 g880(.A (result[0]), .B (n_3), .Y (n_9));
  NOR2XL g881(.A (n_0), .B (n_5), .Y (n_8));
  AOI22XL g882(.A0 (A[2]), .A1 (B[1]), .B0 (A[3]), .B1 (B[0]), .Y
       (n_7));
  AOI22XL g883(.A0 (A[1]), .A1 (B[0]), .B0 (A[0]), .B1 (B[1]), .Y
       (n_6));
  NAND2XL g884(.A (B[3]), .B (A[0]), .Y (n_5));
  AND2X1 g885(.A (B[0]), .B (A[0]), .Y (result[0]));
  AND2X1 g886(.A (B[1]), .B (A[1]), .Y (n_3));
  NAND2XL g887(.A (B[2]), .B (A[0]), .Y (n_2));
  AND2X1 g888(.A (A[2]), .B (B[0]), .Y (n_1));
  NAND2XL g889(.A (B[2]), .B (A[1]), .Y (n_0));
  NAND3BXL g2(.AN (n_25), .B (A[3]), .C (B[1]), .Y (n_54));
endmodule

module vedic4_4_3(A, B, result);
  input [3:0] A, B;
  output [7:0] result;
  wire [3:0] A, B;
  wire [7:0] result;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_27, n_28, n_29, n_31, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_42, n_54;
  assign result[7] = 1'b0;
  OAI21XL g848(.A0 (n_38), .A1 (n_29), .B0 (n_42), .Y (result[5]));
  NAND2XL g849(.A (n_29), .B (n_38), .Y (n_42));
  OAI21XL g850(.A0 (n_37), .A1 (n_28), .B0 (n_27), .Y (result[6]));
  OAI21XL g851(.A0 (n_36), .A1 (n_33), .B0 (n_39), .Y (result[4]));
  NAND2XL g852(.A (n_33), .B (n_36), .Y (n_39));
  NAND2XL g853(.A (n_34), .B (n_37), .Y (n_38));
  NAND2XL g854(.A (n_35), .B (n_33), .Y (n_37));
  NAND2XL g855(.A (n_35), .B (n_34), .Y (n_36));
  NAND2BXL g856(.AN (n_31), .B (n_20), .Y (n_35));
  NAND2BXL g857(.AN (n_20), .B (n_31), .Y (n_34));
  ADDFX1 g858(.A (n_23), .B (n_11), .CI (n_24), .CO (n_33), .S
       (result[3]));
  NAND2XL g859(.A (n_18), .B (n_54), .Y (n_31));
  NAND2BXL g861(.AN (n_28), .B (n_27), .Y (n_29));
  NOR2XL g862(.A (n_8), .B (n_25), .Y (n_28));
  NAND2XL g863(.A (n_8), .B (n_25), .Y (n_27));
  AOI21XL g864(.A0 (n_2), .A1 (n_19), .B0 (n_23), .Y (result[2]));
  OAI21XL g865(.A0 (n_17), .A1 (n_16), .B0 (n_10), .Y (n_25));
  OAI21XL g866(.A0 (n_21), .A1 (n_16), .B0 (n_22), .Y (n_24));
  NOR2XL g867(.A (n_2), .B (n_19), .Y (n_23));
  NAND2XL g868(.A (n_16), .B (n_21), .Y (n_22));
  NOR2BXL g869(.AN (n_18), .B (n_17), .Y (n_21));
  NAND3BXL g870(.AN (n_8), .B (B[3]), .C (A[1]), .Y (n_20));
  OAI21XL g871(.A0 (n_14), .A1 (n_9), .B0 (n_16), .Y (n_19));
  NAND2XL g872(.A (n_13), .B (n_15), .Y (n_18));
  NOR2XL g873(.A (n_13), .B (n_15), .Y (n_17));
  NAND2XL g874(.A (n_9), .B (n_14), .Y (n_16));
  NOR2BXL g875(.AN (n_10), .B (n_7), .Y (n_15));
  ADDHXL g876(.A (n_1), .B (n_3), .CO (n_13), .S (n_14));
  NOR2XL g877(.A (n_6), .B (n_9), .Y (result[1]));
  AOI21XL g878(.A0 (n_0), .A1 (n_5), .B0 (n_8), .Y (n_11));
  NAND3XL g879(.A (A[3]), .B (B[1]), .C (n_1), .Y (n_10));
  AND2X1 g880(.A (result[0]), .B (n_3), .Y (n_9));
  NOR2XL g881(.A (n_0), .B (n_5), .Y (n_8));
  AOI22XL g882(.A0 (A[2]), .A1 (B[1]), .B0 (A[3]), .B1 (B[0]), .Y
       (n_7));
  AOI22XL g883(.A0 (A[1]), .A1 (B[0]), .B0 (A[0]), .B1 (B[1]), .Y
       (n_6));
  NAND2XL g884(.A (B[3]), .B (A[0]), .Y (n_5));
  AND2X1 g885(.A (B[0]), .B (A[0]), .Y (result[0]));
  AND2X1 g886(.A (B[1]), .B (A[1]), .Y (n_3));
  NAND2XL g887(.A (B[2]), .B (A[0]), .Y (n_2));
  AND2X1 g888(.A (A[2]), .B (B[0]), .Y (n_1));
  NAND2XL g889(.A (B[2]), .B (A[1]), .Y (n_0));
  NAND3BXL g2(.AN (n_25), .B (A[3]), .C (B[1]), .Y (n_54));
endmodule

module vedic8_8(a, b, product);
  input [7:0] a, b;
  output [15:0] product;
  wire [7:0] a, b;
  wire [15:0] product;
  wire [7:0] p1;
  wire [7:0] p2;
  wire [7:0] p3;
  wire [15:0] temp1;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, carry, overflow,
       sum;
  assign product[0] = 1'b0;
  assign product[1] = 1'b0;
  assign product[2] = 1'b0;
  assign product[3] = 1'b0;
  assign product[4] = 1'b0;
  assign product[5] = 1'b0;
  assign product[6] = 1'b0;
  assign product[7] = 1'b0;
  assign product[8] = 1'b0;
  assign product[9] = 1'b0;
  assign product[10] = 1'b0;
  assign product[11] = 1'b0;
  assign product[12] = 1'b0;
  assign product[13] = 1'b0;
  assign product[14] = 1'b0;
  compressor6_3 c1(1'b0, p1[3], p2[3], 1'b0, p1[4], p2[4], sum, carry,
       overflow);
  csa_tree_add_85_52_group_59 csa_tree_add_85_52_groupi(.in_0
       ({overflow, carry, sum}), .in_1 ({1'b0, p3[6:0], 8'b00000000}),
       .in_2 ({5'b00000, p2[6:0], 4'b0000}), .in_3 ({1'b0,
       temp1[6:0]}), .in_4 ({5'b00000, p1[6:0], 4'b0000}), .out_0
       ({product[15], UNCONNECTED, UNCONNECTED0, UNCONNECTED1,
       UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9,
       UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13}));
  vedic4_4 vm1(a[3:0], b[3:0], {UNCONNECTED14, temp1[6:0]});
  vedic4_4_1 vm2(a[3:0], b[7:4], {UNCONNECTED15, p1[6:0]});
  vedic4_4_2 vm3(a[7:4], b[3:0], {UNCONNECTED16, p2[6:0]});
  vedic4_4_3 vm4(a[7:4], b[7:4], {UNCONNECTED17, p3[6:0]});
endmodule

module hybrid_mac(activation, weight, clk, reset, mac_result);
  input [7:0] activation, weight;
  input clk, reset;
  output [31:0] mac_result;
  wire [7:0] activation, weight;
  wire clk, reset;
  wire [31:0] mac_result;
  wire [31:0] reduction_result;
  wire [15:0] product;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25;
  wire UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, UNCONNECTED29,
       UNCONNECTED30, UNCONNECTED31, UNCONNECTED32, UNCONNECTED33;
  wire UNCONNECTED34, UNCONNECTED35, UNCONNECTED36, UNCONNECTED37,
       UNCONNECTED38, UNCONNECTED39, UNCONNECTED40;
  accumulator acc(.clk (clk), .reset (reset), .input_data
       ({reduction_result[31:8], 7'b0000000, product[15]}),
       .accumulated_result (mac_result));
  reduction_unit_with_6_3 hreduce(.A (16'b0000000000000000), .B
       (16'b0000000000000000), .C (16'b0000000000000000), .D
       (16'b0000000000000000), .E (16'b0000000000000000), .F
       (16'b0000000000000000), .G (16'b0000000000000000), .H
       (16'b0000000000000000), .Result ({reduction_result[31:8],
       UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25}));
  vedic8_8 vedic_mult(.a (activation), .b (weight), .product
       ({product[15], UNCONNECTED26, UNCONNECTED27, UNCONNECTED28,
       UNCONNECTED29, UNCONNECTED30, UNCONNECTED31, UNCONNECTED32,
       UNCONNECTED33, UNCONNECTED34, UNCONNECTED35, UNCONNECTED36,
       UNCONNECTED37, UNCONNECTED38, UNCONNECTED39, UNCONNECTED40}));
endmodule

