
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/hybrid_mac 

module add_unsigned_28(A, B, Z);
  input [31:0] A, B;
  output [31:0] Z;
  wire [31:0] A, B;
  wire [31:0] Z;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_203, n_204;
  wire n_205, n_206, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_216, n_217, n_218, n_219, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_309;
  AOI21X1 g969(.A0 (n_103), .A1 (n_224), .B0 (n_135), .Y (n_251));
  OAI21X1 g971(.A0 (n_72), .A1 (n_223), .B0 (n_63), .Y (n_250));
  AOI31X1 g973(.A0 (n_159), .A1 (n_160), .A2 (n_224), .B0 (n_221), .Y
       (n_249));
  OAI21X1 g975(.A0 (n_190), .A1 (n_223), .B0 (n_233), .Y (n_248));
  OAI21X1 g977(.A0 (n_166), .A1 (n_223), .B0 (n_211), .Y (n_247));
  AOI31X1 g979(.A0 (n_140), .A1 (n_159), .A2 (n_224), .B0 (n_219), .Y
       (n_246));
  OAI21X1 g981(.A0 (n_187), .A1 (n_223), .B0 (n_222), .Y (n_245));
  OAI21X1 g983(.A0 (n_189), .A1 (n_223), .B0 (n_232), .Y (n_244));
  OAI21X1 g985(.A0 (n_168), .A1 (n_223), .B0 (n_212), .Y (n_243));
  OAI21X1 g987(.A0 (n_157), .A1 (n_223), .B0 (n_199), .Y (n_242));
  OAI21X1 g989(.A0 (n_149), .A1 (n_223), .B0 (n_185), .Y (n_241));
  OAI21X1 g991(.A0 (n_142), .A1 (n_223), .B0 (n_182), .Y (n_240));
  OAI21X1 g993(.A0 (n_158), .A1 (n_223), .B0 (n_203), .Y (n_239));
  OAI21X1 g995(.A0 (n_188), .A1 (n_223), .B0 (n_226), .Y (n_238));
  OAI21X1 g1004(.A0 (n_186), .A1 (n_223), .B0 (n_229), .Y (n_237));
  MXI2XL g1005(.A (n_223), .B (n_224), .S0 (n_115), .Y (Z[16]));
  OAI21X1 g1006(.A0 (n_112), .A1 (n_206), .B0 (n_137), .Y (n_235));
  OAI21X1 g1007(.A0 (n_78), .A1 (n_206), .B0 (n_86), .Y (n_234));
  AOI21XL g1008(.A0 (n_123), .A1 (n_204), .B0 (n_134), .Y (n_233));
  OA21XL g1009(.A0 (n_43), .A1 (n_203), .B0 (n_70), .Y (n_232));
  OAI21X1 g1010(.A0 (n_163), .A1 (n_206), .B0 (n_209), .Y (n_231));
  OAI21X1 g1011(.A0 (n_167), .A1 (n_206), .B0 (n_210), .Y (n_230));
  AOI21XL g1012(.A0 (n_143), .A1 (n_204), .B0 (n_177), .Y (n_229));
  OAI21X1 g1013(.A0 (n_156), .A1 (n_206), .B0 (n_198), .Y (n_228));
  OAI21X1 g1014(.A0 (n_147), .A1 (n_206), .B0 (n_184), .Y (n_227));
  AOI21XL g1015(.A0 (n_155), .A1 (n_204), .B0 (n_200), .Y (n_226));
  OAI21X1 g1016(.A0 (n_153), .A1 (n_206), .B0 (n_178), .Y (n_225));
  CLKINVX3 g1017(.A (n_224), .Y (n_223));
  NAND2X2 g1018(.A (n_205), .B (n_216), .Y (n_224));
  AOI221X1 g1019(.A0 (n_95), .A1 (n_177), .B0 (n_170), .B1 (n_204), .C0
       (n_139), .Y (n_222));
  OAI211X1 g1020(.A0 (n_62), .A1 (n_176), .B0 (n_53), .C0 (n_218), .Y
       (n_221));
  MXI2XL g1021(.A (n_206), .B (n_309), .S0 (n_125), .Y (Z[8]));
  OAI211X1 g1022(.A0 (n_52), .A1 (n_133), .B0 (n_64), .C0 (n_217), .Y
       (n_219));
  NAND2XL g1023(.A (n_160), .B (n_204), .Y (n_218));
  NAND2XL g1024(.A (n_140), .B (n_204), .Y (n_217));
  NAND2XL g1025(.A (n_169), .B (n_309), .Y (n_216));
  OAI21XL g1026(.A0 (n_197), .A1 (n_87), .B0 (n_213), .Y (Z[5]));
  OAI21XL g1027(.A0 (n_194), .A1 (n_90), .B0 (n_208), .Y (Z[7]));
  NAND2XL g1029(.A (n_87), .B (n_197), .Y (n_213));
  AOI21X1 g1030(.A0 (n_98), .A1 (n_181), .B0 (n_138), .Y (n_212));
  OA21X1 g1031(.A0 (n_69), .A1 (n_182), .B0 (n_41), .Y (n_211));
  AOI21X1 g1032(.A0 (n_119), .A1 (n_179), .B0 (n_132), .Y (n_210));
  OA21XL g1033(.A0 (n_74), .A1 (n_178), .B0 (n_68), .Y (n_209));
  NAND2XL g1034(.A (n_90), .B (n_194), .Y (n_208));
  CLKINVX1 g1035(.A (n_309), .Y (n_206));
  AOI21X1 g1037(.A0 (n_151), .A1 (n_179), .B0 (n_180), .Y (n_205));
  CLKINVX1 g1038(.A (n_204), .Y (n_203));
  OAI21X1 g1039(.A0 (n_148), .A1 (n_182), .B0 (n_175), .Y (n_204));
  OAI21X1 g1040(.A0 (n_89), .A1 (n_192), .B0 (n_195), .Y (Z[3]));
  XOR2XL g1041(.A (n_93), .B (n_183), .Y (Z[4]));
  OAI211X1 g1042(.A0 (n_146), .A1 (n_176), .B0 (n_37), .C0 (n_161), .Y
       (n_200));
  AOI221X1 g1043(.A0 (n_34), .A1 (n_138), .B0 (n_154), .B1 (n_181), .C0
       (n_55), .Y (n_199));
  AOI221X1 g1044(.A0 (n_59), .A1 (n_132), .B0 (n_145), .B1 (n_179), .C0
       (n_48), .Y (n_198));
  NAND2XL g1045(.A (n_44), .B (n_183), .Y (n_197));
  AND2X1 g1047(.A (n_24), .B (n_183), .Y (n_196));
  NAND2XL g1048(.A (n_89), .B (n_192), .Y (n_195));
  NAND3X1 g1049(.A (n_32), .B (n_24), .C (n_183), .Y (n_194));
  OAI21XL g1050(.A0 (n_173), .A1 (n_92), .B0 (n_191), .Y (Z[2]));
  NAND2BX1 g1051(.AN (n_173), .B (n_75), .Y (n_192));
  NAND2XL g1052(.A (n_173), .B (n_92), .Y (n_191));
  NAND2XL g1053(.A (n_123), .B (n_159), .Y (n_190));
  NAND2BXL g1054(.AN (n_43), .B (n_159), .Y (n_189));
  NAND2XL g1055(.A (n_159), .B (n_155), .Y (n_188));
  NAND2XL g1056(.A (n_159), .B (n_170), .Y (n_187));
  NAND2XL g1057(.A (n_143), .B (n_159), .Y (n_186));
  AOI21X1 g1058(.A0 (n_46), .A1 (n_135), .B0 (n_38), .Y (n_185));
  OA21XL g1059(.A0 (n_79), .A1 (n_137), .B0 (n_81), .Y (n_184));
  NOR2X1 g1064(.A (n_171), .B (n_173), .Y (n_183));
  CLKINVX1 g1065(.A (n_182), .Y (n_181));
  AOI21X1 g1066(.A0 (n_135), .A1 (n_106), .B0 (n_131), .Y (n_182));
  OAI211X1 g1067(.A0 (n_49), .A1 (n_80), .B0 (n_66), .C0 (n_164), .Y
       (n_180));
  CLKINVX1 g1068(.A (n_179), .Y (n_178));
  OAI211X1 g1069(.A0 (n_81), .A1 (n_76), .B0 (n_51), .C0 (n_172), .Y
       (n_179));
  CLKINVX1 g1070(.A (n_177), .Y (n_176));
  OAI211X1 g1071(.A0 (n_64), .A1 (n_42), .B0 (n_47), .C0 (n_165), .Y
       (n_177));
  AOI21X1 g1072(.A0 (n_126), .A1 (n_138), .B0 (n_130), .Y (n_175));
  OAI21XL g1073(.A0 (n_91), .A1 (n_30), .B0 (n_162), .Y (Z[1]));
  NAND2XL g1076(.A (n_29), .B (n_30), .Y (n_173));
  NAND2XL g1077(.A (n_136), .B (n_122), .Y (n_172));
  NAND2XL g1078(.A (n_28), .B (n_75), .Y (n_171));
  AND2X1 g1079(.A (n_95), .B (n_143), .Y (n_170));
  NOR2XL g1080(.A (n_150), .B (n_153), .Y (n_169));
  NAND2XL g1081(.A (n_98), .B (n_141), .Y (n_168));
  NAND2XL g1082(.A (n_119), .B (n_152), .Y (n_167));
  NAND2BXL g1083(.AN (n_69), .B (n_141), .Y (n_166));
  NAND2XL g1084(.A (n_134), .B (n_114), .Y (n_165));
  NAND2XL g1085(.A (n_102), .B (n_132), .Y (n_164));
  NAND2BXL g1086(.AN (n_74), .B (n_152), .Y (n_163));
  NAND2XL g1087(.A (n_30), .B (n_91), .Y (n_162));
  NAND2BX1 g1088(.AN (n_84), .B (n_139), .Y (n_161));
  NOR2XL g1089(.A (n_62), .B (n_144), .Y (n_160));
  INVXL g1090(.A (n_159), .Y (n_158));
  NOR2XL g1091(.A (n_148), .B (n_142), .Y (n_159));
  NAND2XL g1096(.A (n_154), .B (n_141), .Y (n_157));
  NAND2XL g1097(.A (n_145), .B (n_152), .Y (n_156));
  NOR2XL g1098(.A (n_146), .B (n_144), .Y (n_155));
  AND2X1 g1099(.A (n_34), .B (n_98), .Y (n_154));
  CLKINVX1 g1100(.A (n_153), .Y (n_152));
  NAND2XL g1101(.A (n_113), .B (n_122), .Y (n_153));
  INVXL g1102(.A (n_150), .Y (n_151));
  NAND2XL g1103(.A (n_119), .B (n_102), .Y (n_150));
  NAND2XL g1104(.A (n_46), .B (n_103), .Y (n_149));
  NAND2XL g1105(.A (n_98), .B (n_126), .Y (n_148));
  NAND2BXL g1106(.AN (n_79), .B (n_113), .Y (n_147));
  NAND2BX1 g1107(.AN (n_84), .B (n_95), .Y (n_146));
  AND2X1 g1108(.A (n_59), .B (n_119), .Y (n_145));
  CLKINVX1 g1109(.A (n_144), .Y (n_143));
  NAND2XL g1110(.A (n_123), .B (n_114), .Y (n_144));
  CLKINVX1 g1111(.A (n_142), .Y (n_141));
  NAND2XL g1112(.A (n_103), .B (n_106), .Y (n_142));
  NOR2BX1 g1113(.AN (n_123), .B (n_52), .Y (n_140));
  OAI21X1 g1114(.A0 (n_53), .A1 (n_77), .B0 (n_71), .Y (n_139));
  OAI21X1 g1115(.A0 (n_41), .A1 (n_67), .B0 (n_40), .Y (n_138));
  CLKINVX1 g1116(.A (n_136), .Y (n_137));
  OAI21X1 g1117(.A0 (n_86), .A1 (n_65), .B0 (n_35), .Y (n_136));
  OAI21X1 g1118(.A0 (n_63), .A1 (n_83), .B0 (n_36), .Y (n_135));
  INVXL g1119(.A (n_134), .Y (n_133));
  OAI21X1 g1120(.A0 (n_70), .A1 (n_85), .B0 (n_61), .Y (n_134));
  OAI21X1 g1121(.A0 (n_68), .A1 (n_54), .B0 (n_50), .Y (n_132));
  OAI21X1 g1122(.A0 (n_39), .A1 (n_57), .B0 (n_73), .Y (n_131));
  OAI21X1 g1123(.A0 (n_56), .A1 (n_82), .B0 (n_31), .Y (n_130));
  NAND2BX1 g1125(.AN (n_43), .B (n_70), .Y (n_129));
  NAND2BX1 g1126(.AN (n_84), .B (n_37), .Y (n_128));
  NAND2XL g1127(.A (n_56), .B (n_34), .Y (n_127));
  NOR2XL g1128(.A (n_33), .B (n_82), .Y (n_126));
  NOR2BX1 g1129(.AN (n_86), .B (n_78), .Y (n_125));
  NAND2BX1 g1130(.AN (n_67), .B (n_40), .Y (n_124));
  NOR2XL g1131(.A (n_43), .B (n_85), .Y (n_123));
  NOR2XL g1132(.A (n_79), .B (n_76), .Y (n_122));
  NAND2BX1 g1133(.AN (n_69), .B (n_41), .Y (n_121));
  NAND2BX1 g1134(.AN (n_57), .B (n_73), .Y (n_120));
  NOR2XL g1135(.A (n_74), .B (n_54), .Y (n_119));
  NAND2XL g1136(.A (n_39), .B (n_46), .Y (n_118));
  NAND2BX1 g1137(.AN (n_83), .B (n_36), .Y (n_117));
  NOR2BX1 g1139(.AN (n_51), .B (n_76), .Y (n_116));
  NOR2BX1 g1140(.AN (n_63), .B (n_72), .Y (n_115));
  NOR2XL g1141(.A (n_52), .B (n_42), .Y (n_114));
  INVXL g1142(.A (n_113), .Y (n_112));
  NOR2XL g1143(.A (n_78), .B (n_65), .Y (n_113));
  NAND2BX1 g1144(.AN (n_62), .B (n_53), .Y (n_111));
  NAND2BX1 g1146(.AN (n_54), .B (n_50), .Y (n_110));
  NAND2BX1 g1148(.AN (n_79), .B (n_81), .Y (n_109));
  NAND2BX1 g1150(.AN (n_74), .B (n_68), .Y (n_108));
  NAND2BX1 g1152(.AN (n_80), .B (n_66), .Y (n_107));
  NOR2XL g1153(.A (n_45), .B (n_57), .Y (n_106));
  NAND2BX1 g1154(.AN (n_77), .B (n_71), .Y (n_105));
  NAND2BX1 g1155(.AN (n_82), .B (n_31), .Y (n_104));
  NOR2XL g1156(.A (n_72), .B (n_83), .Y (n_103));
  NOR2XL g1157(.A (n_58), .B (n_80), .Y (n_102));
  NAND2BX1 g1158(.AN (n_42), .B (n_47), .Y (n_101));
  NAND2XL g1160(.A (n_49), .B (n_59), .Y (n_100));
  NAND2BX1 g1161(.AN (n_52), .B (n_64), .Y (n_99));
  NOR2XL g1162(.A (n_69), .B (n_67), .Y (n_98));
  NAND2BX1 g1163(.AN (n_85), .B (n_61), .Y (n_97));
  NAND2BX1 g1165(.AN (n_65), .B (n_35), .Y (n_96));
  NOR2XL g1166(.A (n_62), .B (n_77), .Y (n_95));
  OAI21XL g1167(.A0 (B[0]), .A1 (A[6]), .B0 (n_32), .Y (n_94));
  OAI21X1 g1168(.A0 (A[4]), .A1 (B[0]), .B0 (n_44), .Y (n_93));
  OAI21X1 g1169(.A0 (A[2]), .A1 (B[0]), .B0 (n_75), .Y (n_92));
  OA21X1 g1170(.A0 (A[1]), .A1 (B[0]), .B0 (n_29), .Y (n_91));
  OAI21X1 g1171(.A0 (A[7]), .A1 (B[0]), .B0 (n_26), .Y (n_90));
  OAI21X1 g1172(.A0 (A[3]), .A1 (B[0]), .B0 (n_28), .Y (n_89));
  OAI21X1 g1173(.A0 (B[31]), .A1 (A[31]), .B0 (n_60), .Y (n_88));
  OAI21X1 g1174(.A0 (A[5]), .A1 (B[0]), .B0 (n_27), .Y (n_87));
  NAND2XL g1176(.A (B[8]), .B (A[8]), .Y (n_86));
  NOR2XL g1177(.A (B[25]), .B (A[25]), .Y (n_85));
  NOR2XL g1178(.A (B[30]), .B (A[30]), .Y (n_84));
  NOR2XL g1179(.A (B[17]), .B (A[17]), .Y (n_83));
  NOR2XL g1180(.A (B[23]), .B (A[23]), .Y (n_82));
  NAND2XL g1181(.A (B[10]), .B (A[10]), .Y (n_81));
  NOR2XL g1182(.A (B[15]), .B (A[15]), .Y (n_80));
  NOR2XL g1183(.A (B[10]), .B (A[10]), .Y (n_79));
  NOR2XL g1184(.A (B[8]), .B (A[8]), .Y (n_78));
  NOR2XL g1185(.A (B[29]), .B (A[29]), .Y (n_77));
  NOR2XL g1186(.A (B[11]), .B (A[11]), .Y (n_76));
  NAND2XL g1187(.A (A[2]), .B (B[0]), .Y (n_75));
  NOR2XL g1188(.A (B[12]), .B (A[12]), .Y (n_74));
  NAND2XL g1189(.A (B[19]), .B (A[19]), .Y (n_73));
  NOR2XL g1190(.A (B[16]), .B (A[16]), .Y (n_72));
  NAND2XL g1191(.A (B[29]), .B (A[29]), .Y (n_71));
  NAND2XL g1192(.A (B[24]), .B (A[24]), .Y (n_70));
  NOR2XL g1193(.A (B[20]), .B (A[20]), .Y (n_69));
  NAND2XL g1194(.A (B[12]), .B (A[12]), .Y (n_68));
  NOR2XL g1195(.A (B[21]), .B (A[21]), .Y (n_67));
  NAND2XL g1196(.A (B[15]), .B (A[15]), .Y (n_66));
  NOR2XL g1197(.A (B[9]), .B (A[9]), .Y (n_65));
  NAND2XL g1198(.A (B[26]), .B (A[26]), .Y (n_64));
  NAND2XL g1199(.A (B[16]), .B (A[16]), .Y (n_63));
  NOR2XL g1200(.A (B[28]), .B (A[28]), .Y (n_62));
  NAND2XL g1201(.A (B[25]), .B (A[25]), .Y (n_61));
  NAND2XL g1202(.A (B[31]), .B (A[31]), .Y (n_60));
  CLKINVX1 g1203(.A (n_58), .Y (n_59));
  NOR2XL g1204(.A (B[14]), .B (A[14]), .Y (n_58));
  NOR2XL g1205(.A (B[19]), .B (A[19]), .Y (n_57));
  INVXL g1206(.A (n_56), .Y (n_55));
  NAND2XL g1207(.A (B[22]), .B (A[22]), .Y (n_56));
  NOR2XL g1208(.A (B[13]), .B (A[13]), .Y (n_54));
  NAND2XL g1209(.A (B[28]), .B (A[28]), .Y (n_53));
  NOR2XL g1210(.A (B[26]), .B (A[26]), .Y (n_52));
  NAND2XL g1211(.A (B[11]), .B (A[11]), .Y (n_51));
  NAND2XL g1212(.A (B[13]), .B (A[13]), .Y (n_50));
  INVXL g1213(.A (n_49), .Y (n_48));
  NAND2XL g1214(.A (B[14]), .B (A[14]), .Y (n_49));
  NAND2XL g1215(.A (B[27]), .B (A[27]), .Y (n_47));
  CLKINVX1 g1216(.A (n_45), .Y (n_46));
  NOR2XL g1217(.A (B[18]), .B (A[18]), .Y (n_45));
  NAND2XL g1219(.A (A[4]), .B (B[0]), .Y (n_44));
  NOR2XL g1220(.A (B[24]), .B (A[24]), .Y (n_43));
  NOR2XL g1221(.A (B[27]), .B (A[27]), .Y (n_42));
  NAND2XL g1222(.A (B[20]), .B (A[20]), .Y (n_41));
  NAND2XL g1223(.A (B[21]), .B (A[21]), .Y (n_40));
  INVXL g1224(.A (n_39), .Y (n_38));
  NAND2XL g1225(.A (B[18]), .B (A[18]), .Y (n_39));
  NAND2XL g1226(.A (B[30]), .B (A[30]), .Y (n_37));
  NAND2XL g1227(.A (B[17]), .B (A[17]), .Y (n_36));
  NAND2XL g1228(.A (B[9]), .B (A[9]), .Y (n_35));
  CLKINVX1 g1229(.A (n_33), .Y (n_34));
  NOR2XL g1230(.A (B[22]), .B (A[22]), .Y (n_33));
  NAND2XL g1232(.A (A[6]), .B (B[0]), .Y (n_32));
  NAND2XL g1233(.A (B[23]), .B (A[23]), .Y (n_31));
  NAND2XL g1234(.A (A[0]), .B (B[0]), .Y (n_30));
  NAND2XL g1235(.A (A[1]), .B (B[0]), .Y (n_29));
  NAND2XL g1236(.A (A[3]), .B (B[0]), .Y (n_28));
  NAND2XL g1237(.A (A[5]), .B (B[0]), .Y (n_27));
  NAND2XL g1238(.A (A[7]), .B (B[0]), .Y (n_26));
  AND2X1 g1240(.A (n_44), .B (n_27), .Y (n_24));
  XOR2XL g1241(.A (n_251), .B (n_118), .Y (Z[18]));
  XNOR2XL g1242(.A (n_250), .B (n_117), .Y (Z[17]));
  XOR2XL g1243(.A (n_249), .B (n_105), .Y (Z[29]));
  XNOR2XL g1244(.A (n_248), .B (n_99), .Y (Z[26]));
  XNOR2XL g1245(.A (n_247), .B (n_124), .Y (Z[21]));
  XOR2XL g1246(.A (n_246), .B (n_101), .Y (Z[27]));
  XNOR2XL g1247(.A (n_245), .B (n_128), .Y (Z[30]));
  XNOR2XL g1248(.A (n_244), .B (n_97), .Y (Z[25]));
  XNOR2XL g1249(.A (n_243), .B (n_127), .Y (Z[22]));
  XNOR2XL g1250(.A (n_242), .B (n_104), .Y (Z[23]));
  XNOR2XL g1251(.A (n_241), .B (n_120), .Y (Z[19]));
  XNOR2XL g1252(.A (n_240), .B (n_121), .Y (Z[20]));
  XNOR2XL g1253(.A (n_239), .B (n_129), .Y (Z[24]));
  XNOR2XL g1254(.A (n_238), .B (n_88), .Y (Z[31]));
  XNOR2XL g1255(.A (n_237), .B (n_111), .Y (Z[28]));
  XOR2XL g1256(.A (n_94), .B (n_196), .Y (Z[6]));
  XOR2XL g1257(.A (n_116), .B (n_227), .Y (Z[11]));
  XNOR2XL g1258(.A (n_110), .B (n_231), .Y (Z[13]));
  XNOR2XL g1259(.A (n_109), .B (n_235), .Y (Z[10]));
  XNOR2XL g1260(.A (n_108), .B (n_225), .Y (Z[12]));
  XNOR2XL g1261(.A (n_107), .B (n_228), .Y (Z[15]));
  XNOR2XL g1262(.A (n_100), .B (n_230), .Y (Z[14]));
  XNOR2XL g1263(.A (n_96), .B (n_234), .Y (Z[9]));
  XOR2XL g1264(.A (B[0]), .B (A[0]), .Y (Z[0]));
  NAND3X1 g1265(.A (n_32), .B (n_26), .C (n_196), .Y (n_309));
endmodule

module accumulator(clk, reset, input_data, accumulated_result);
  input clk, reset;
  input [31:0] input_data;
  output [31:0] accumulated_result;
  wire clk, reset;
  wire [31:0] input_data;
  wire [31:0] accumulated_result;
  wire n_0, n_11, n_22, n_26, n_37, n_48, n_59, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_91;
  add_unsigned_28 add_17_54(.A (accumulated_result), .B
       ({input_data[31:8], 7'b0000000, input_data[0]}), .Z ({n_64,
       n_65, n_66, n_67, n_68, n_70, n_71, n_72, n_73, n_74, n_75,
       n_76, n_77, n_78, n_79, n_81, n_82, n_83, n_84, n_85, n_86,
       n_87, n_88, n_89, n_91, n_11, n_22, n_26, n_37, n_48, n_59,
       n_69}));
  INVXL g3(.A (reset), .Y (n_0));
  DFFRHQX1 \accumulated_result_reg[0] (.RN (n_0), .CK (clk), .D (n_69),
       .Q (accumulated_result[0]));
  DFFRHQX1 \accumulated_result_reg[10] (.RN (n_0), .CK (clk), .D
       (n_87), .Q (accumulated_result[10]));
  DFFRHQX1 \accumulated_result_reg[11] (.RN (n_0), .CK (clk), .D
       (n_86), .Q (accumulated_result[11]));
  DFFRHQX1 \accumulated_result_reg[12] (.RN (n_0), .CK (clk), .D
       (n_85), .Q (accumulated_result[12]));
  DFFRHQX1 \accumulated_result_reg[13] (.RN (n_0), .CK (clk), .D
       (n_84), .Q (accumulated_result[13]));
  DFFRHQX1 \accumulated_result_reg[5] (.RN (n_0), .CK (clk), .D (n_22),
       .Q (accumulated_result[5]));
  DFFRHQX1 \accumulated_result_reg[14] (.RN (n_0), .CK (clk), .D
       (n_83), .Q (accumulated_result[14]));
  DFFRHQX1 \accumulated_result_reg[15] (.RN (n_0), .CK (clk), .D
       (n_82), .Q (accumulated_result[15]));
  DFFRHQX1 \accumulated_result_reg[16] (.RN (n_0), .CK (clk), .D
       (n_81), .Q (accumulated_result[16]));
  DFFRHQX1 \accumulated_result_reg[30] (.RN (n_0), .CK (clk), .D
       (n_65), .Q (accumulated_result[30]));
  DFFRHQX1 \accumulated_result_reg[17] (.RN (n_0), .CK (clk), .D
       (n_79), .Q (accumulated_result[17]));
  DFFRHQX1 \accumulated_result_reg[18] (.RN (n_0), .CK (clk), .D
       (n_78), .Q (accumulated_result[18]));
  DFFRHQX1 \accumulated_result_reg[19] (.RN (n_0), .CK (clk), .D
       (n_77), .Q (accumulated_result[19]));
  DFFRHQX1 \accumulated_result_reg[27] (.RN (n_0), .CK (clk), .D
       (n_68), .Q (accumulated_result[27]));
  DFFRHQX1 \accumulated_result_reg[1] (.RN (n_0), .CK (clk), .D (n_59),
       .Q (accumulated_result[1]));
  DFFRHQX1 \accumulated_result_reg[20] (.RN (n_0), .CK (clk), .D
       (n_76), .Q (accumulated_result[20]));
  DFFRHQX1 \accumulated_result_reg[21] (.RN (n_0), .CK (clk), .D
       (n_75), .Q (accumulated_result[21]));
  DFFRHQX1 \accumulated_result_reg[22] (.RN (n_0), .CK (clk), .D
       (n_74), .Q (accumulated_result[22]));
  DFFRHQX1 \accumulated_result_reg[23] (.RN (n_0), .CK (clk), .D
       (n_73), .Q (accumulated_result[23]));
  DFFRHQX1 \accumulated_result_reg[24] (.RN (n_0), .CK (clk), .D
       (n_72), .Q (accumulated_result[24]));
  DFFRHQX1 \accumulated_result_reg[25] (.RN (n_0), .CK (clk), .D
       (n_71), .Q (accumulated_result[25]));
  DFFRHQX1 \accumulated_result_reg[26] (.RN (n_0), .CK (clk), .D
       (n_70), .Q (accumulated_result[26]));
  DFFRHQX1 \accumulated_result_reg[28] (.RN (n_0), .CK (clk), .D
       (n_67), .Q (accumulated_result[28]));
  DFFRHQX1 \accumulated_result_reg[29] (.RN (n_0), .CK (clk), .D
       (n_66), .Q (accumulated_result[29]));
  DFFRHQX1 \accumulated_result_reg[2] (.RN (n_0), .CK (clk), .D (n_48),
       .Q (accumulated_result[2]));
  DFFRHQX1 \accumulated_result_reg[31] (.RN (n_0), .CK (clk), .D
       (n_64), .Q (accumulated_result[31]));
  DFFRHQX1 \accumulated_result_reg[3] (.RN (n_0), .CK (clk), .D (n_37),
       .Q (accumulated_result[3]));
  DFFRHQX1 \accumulated_result_reg[4] (.RN (n_0), .CK (clk), .D (n_26),
       .Q (accumulated_result[4]));
  DFFRHQX1 \accumulated_result_reg[6] (.RN (n_0), .CK (clk), .D (n_11),
       .Q (accumulated_result[6]));
  DFFRHQX1 \accumulated_result_reg[7] (.RN (n_0), .CK (clk), .D (n_91),
       .Q (accumulated_result[7]));
  DFFRHQX1 \accumulated_result_reg[8] (.RN (n_0), .CK (clk), .D (n_89),
       .Q (accumulated_result[8]));
  DFFRHQX1 \accumulated_result_reg[9] (.RN (n_0), .CK (clk), .D (n_88),
       .Q (accumulated_result[9]));
endmodule

module reduction_unit_with_6_3(A, B, C, D, E, F, G, H, Result);
  input [15:0] A, B, C, D, E, F, G, H;
  output [31:0] Result;
  wire [15:0] A, B, C, D, E, F, G, H;
  wire [31:0] Result;
  assign Result[0] = 1'b0;
  assign Result[1] = 1'b0;
  assign Result[2] = 1'b0;
  assign Result[3] = 1'b0;
  assign Result[4] = 1'b0;
  assign Result[5] = 1'b0;
  assign Result[6] = 1'b0;
  assign Result[7] = 1'b0;
endmodule

module compressor6_3(a, b, c, d, e, f, sum, carry, overflow);
  input a, b, c, d, e, f;
  output sum, carry, overflow;
  wire a, b, c, d, e, f;
  wire sum, carry, overflow;
  wire n_0, n_1, n_2, n_3;
  ADDHXL g62(.A (n_0), .B (n_2), .CO (overflow), .S (carry));
  CLKXOR2X1 g63(.A (n_1), .B (n_3), .Y (sum));
  ADDHXL g64(.A (e), .B (f), .CO (n_2), .S (n_3));
  ADDHXL g65(.A (b), .B (c), .CO (n_0), .S (n_1));
endmodule

module csa_tree_add_83_52_group_59(in_0, in_1, in_2, in_3, in_4, out_0);
  input [2:0] in_0;
  input [15:0] in_1, in_2, in_4;
  input [7:0] in_3;
  output [15:0] out_0;
  wire [2:0] in_0;
  wire [15:0] in_1, in_2, in_4;
  wire [7:0] in_3;
  wire [15:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44;
  assign out_0[0] = 1'b0;
  assign out_0[1] = 1'b0;
  assign out_0[2] = 1'b0;
  assign out_0[3] = 1'b0;
  assign out_0[4] = 1'b0;
  assign out_0[5] = 1'b0;
  assign out_0[6] = 1'b0;
  assign out_0[7] = 1'b0;
  assign out_0[8] = 1'b0;
  assign out_0[9] = 1'b0;
  assign out_0[10] = 1'b0;
  assign out_0[11] = 1'b0;
  assign out_0[12] = 1'b0;
  assign out_0[13] = 1'b0;
  assign out_0[14] = 1'b0;
  NOR2XL g699(.A (n_1), .B (n_44), .Y (out_0[15]));
  AOI32XL g700(.A0 (n_12), .A1 (in_1[11]), .A2 (in_1[12]), .B0 (n_43),
       .B1 (in_1[12]), .Y (n_44));
  OAI21XL g701(.A0 (n_41), .A1 (n_15), .B0 (n_42), .Y (n_43));
  OAI2BB1XL g702(.A0N (n_15), .A1N (n_41), .B0 (n_23), .Y (n_42));
  AOI22XL g703(.A0 (n_40), .A1 (n_25), .B0 (n_39), .B1 (n_24), .Y
       (n_41));
  OR2X1 g704(.A (n_24), .B (n_39), .Y (n_40));
  OAI2BB1XL g705(.A0N (n_26), .A1N (n_37), .B0 (n_38), .Y (n_39));
  OAI211XL g706(.A0 (n_37), .A1 (n_26), .B0 (in_4[8]), .C0 (n_6), .Y
       (n_38));
  OAI2BB1XL g707(.A0N (n_29), .A1N (n_16), .B0 (n_36), .Y (n_37));
  OAI21XL g708(.A0 (n_16), .A1 (n_29), .B0 (n_35), .Y (n_36));
  OAI2BB1XL g709(.A0N (n_30), .A1N (n_33), .B0 (n_34), .Y (n_35));
  OAI21XL g710(.A0 (n_33), .A1 (n_30), .B0 (n_20), .Y (n_34));
  OAI21XL g711(.A0 (n_31), .A1 (n_22), .B0 (n_32), .Y (n_33));
  OAI2BB1XL g712(.A0N (n_22), .A1N (n_31), .B0 (n_27), .Y (n_32));
  AOI32XL g713(.A0 (n_28), .A1 (n_8), .A2 (in_3[4]), .B0 (n_19), .B1
       (n_28), .Y (n_31));
  ADDFX1 g714(.A (in_2[7]), .B (n_3), .CI (in_4[7]), .CO (n_29), .S
       (n_30));
  ADDFX1 g715(.A (n_10), .B (n_7), .CI (in_3[5]), .CO (n_27), .S
       (n_28));
  ADDFX1 g716(.A (in_4[9]), .B (n_5), .CI (n_14), .CO (n_25), .S
       (n_26));
  ADDFX1 g717(.A (n_13), .B (in_4[10]), .CI (n_11), .CO (n_23), .S
       (n_24));
  CLKINVX1 g718(.A (n_21), .Y (n_22));
  ADDFX1 g719(.A (n_4), .B (n_9), .CI (in_3[6]), .CO (n_20), .S (n_21));
  NOR3XL g720(.A (n_18), .B (n_0), .C (n_17), .Y (n_19));
  OAI21XL g721(.A0 (in_3[4]), .A1 (n_8), .B0 (in_3[3]), .Y (n_18));
  AOI222XL g722(.A0 (in_3[0]), .A1 (n_2), .B0 (in_3[1]), .B1 (in_0[1]),
       .C0 (in_0[2]), .C1 (in_3[2]), .Y (n_17));
  CLKXOR2X1 g723(.A (in_4[8]), .B (n_6), .Y (n_16));
  NOR2XL g724(.A (in_1[11]), .B (n_12), .Y (n_15));
  ADDHXL g725(.A (in_1[9]), .B (in_2[9]), .CO (n_13), .S (n_14));
  ADDHXL g726(.A (in_1[10]), .B (in_2[10]), .CO (n_12), .S (n_11));
  ADDHXL g727(.A (in_4[5]), .B (in_2[5]), .CO (n_9), .S (n_10));
  ADDHXL g728(.A (in_4[4]), .B (in_2[4]), .CO (n_7), .S (n_8));
  ADDHXL g729(.A (in_1[8]), .B (in_2[8]), .CO (n_5), .S (n_6));
  ADDHXL g730(.A (in_4[6]), .B (in_2[6]), .CO (n_3), .S (n_4));
  OA21X1 g731(.A0 (in_3[1]), .A1 (in_0[1]), .B0 (in_0[0]), .Y (n_2));
  NAND2XL g732(.A (in_1[14]), .B (in_1[13]), .Y (n_1));
  NOR2XL g733(.A (in_3[2]), .B (in_0[2]), .Y (n_0));
endmodule

module vedic4_4(a, b, product);
  input [3:0] a, b;
  output [7:0] product;
  wire [3:0] a, b;
  wire [7:0] product;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_54, n_55, n_57, n_58, n_60;
  wire n_61;
  assign product[7] = 1'b0;
  NAND2XL g1033(.A (n_48), .B (n_61), .Y (product[6]));
  CLKXOR2X1 g1034(.A (n_44), .B (n_60), .Y (product[5]));
  AOI21XL g1035(.A0 (n_45), .A1 (n_57), .B0 (n_20), .Y (n_61));
  NOR2BXL g1036(.AN (n_48), .B (n_57), .Y (n_60));
  OAI21XL g1037(.A0 (n_55), .A1 (n_50), .B0 (n_58), .Y (product[4]));
  NAND2XL g1038(.A (n_50), .B (n_55), .Y (n_58));
  NOR2XL g1039(.A (n_47), .B (n_55), .Y (n_57));
  INVXL g1040(.A (n_54), .Y (product[3]));
  ADDFX1 g1041(.A (n_51), .B (n_31), .CI (n_49), .CO (n_55), .S (n_54));
  CLKINVX1 g1042(.A (n_52), .Y (product[2]));
  ADDFX1 g1043(.A (n_37), .B (n_13), .CI (n_41), .CO (n_51), .S (n_52));
  NOR2BXL g1044(.AN (n_48), .B (n_47), .Y (n_50));
  XNOR2X1 g1045(.A (n_12), .B (n_40), .Y (n_49));
  NAND2XL g1046(.A (n_42), .B (n_43), .Y (n_48));
  NOR2XL g1047(.A (n_42), .B (n_43), .Y (n_47));
  OAI31XL g1048(.A0 (n_33), .A1 (n_18), .A2 (n_34), .B0 (n_39), .Y
       (product[1]));
  CLKINVX1 g1049(.A (n_44), .Y (n_45));
  AOI211XL g1050(.A0 (n_27), .A1 (n_28), .B0 (n_24), .C0 (n_35), .Y
       (n_44));
  XOR2X1 g1051(.A (n_36), .B (n_28), .Y (n_43));
  NAND2BXL g1052(.AN (n_20), .B (n_38), .Y (n_42));
  AOI21XL g1053(.A0 (n_18), .A1 (n_32), .B0 (n_34), .Y (n_41));
  OAI21XL g1054(.A0 (n_30), .A1 (n_18), .B0 (n_39), .Y (n_40));
  NAND2XL g1055(.A (n_18), .B (n_30), .Y (n_39));
  OAI21XL g1056(.A0 (n_18), .A1 (n_12), .B0 (n_29), .Y (n_38));
  XNOR2X1 g1057(.A (n_14), .B (n_25), .Y (n_37));
  ADDHXL g1058(.A (n_23), .B (n_22), .CO (n_35), .S (n_36));
  NOR2XL g1059(.A (n_4), .B (n_26), .Y (n_34));
  CLKINVX1 g1060(.A (n_32), .Y (n_33));
  NAND2XL g1061(.A (n_4), .B (n_26), .Y (n_32));
  OR2X1 g1062(.A (n_14), .B (n_25), .Y (n_31));
  CLKINVX1 g1063(.A (n_29), .Y (n_30));
  ADDHXL g1064(.A (n_21), .B (n_19), .CO (n_28), .S (n_29));
  OR2X1 g1065(.A (n_22), .B (n_23), .Y (n_27));
  ADDFX1 g1066(.A (n_6), .B (n_9), .CI (n_5), .CO (n_25), .S (n_26));
  AOI21XL g1067(.A0 (n_16), .A1 (n_15), .B0 (n_20), .Y (n_24));
  AND3XL g1068(.A (b[3]), .B (a[1]), .C (n_16), .Y (n_23));
  AND3XL g1069(.A (b[1]), .B (a[3]), .C (n_15), .Y (n_22));
  NOR2BXL g1070(.AN (n_15), .B (n_11), .Y (n_21));
  NOR2XL g1071(.A (n_16), .B (n_15), .Y (n_20));
  NOR2BXL g1072(.AN (n_16), .B (n_10), .Y (n_19));
  ADDHXL g1073(.A (n_2), .B (n_3), .CO (n_18), .S (product[0]));
  NAND3BXL g1074(.AN (n_1), .B (a[1]), .C (b[3]), .Y (n_16));
  NAND3BXL g1075(.AN (n_0), .B (b[1]), .C (a[3]), .Y (n_15));
  XNOR2X1 g1076(.A (n_0), .B (n_1), .Y (n_14));
  XNOR2X1 g1077(.A (n_8), .B (n_7), .Y (n_13));
  NOR2XL g1078(.A (n_7), .B (n_8), .Y (n_12));
  AOI22XL g1079(.A0 (a[2]), .A1 (b[1]), .B0 (a[3]), .B1 (b[0]), .Y
       (n_11));
  AOI22XL g1080(.A0 (a[0]), .A1 (b[3]), .B0 (a[1]), .B1 (b[2]), .Y
       (n_10));
  NAND2XL g1081(.A (b[0]), .B (a[1]), .Y (n_9));
  NAND2XL g1082(.A (b[3]), .B (a[3]), .Y (n_8));
  NAND2XL g1083(.A (b[1]), .B (a[1]), .Y (n_7));
  NAND2XL g1084(.A (b[1]), .B (a[0]), .Y (n_6));
  NAND2XL g1085(.A (b[3]), .B (a[2]), .Y (n_5));
  NAND2XL g1086(.A (b[2]), .B (a[3]), .Y (n_4));
  AND2X1 g1087(.A (b[2]), .B (a[2]), .Y (n_3));
  AND2X1 g1088(.A (b[0]), .B (a[0]), .Y (n_2));
  NAND2XL g1089(.A (a[0]), .B (b[2]), .Y (n_1));
  NAND2XL g1090(.A (b[0]), .B (a[2]), .Y (n_0));
endmodule

module vedic4_4_1(a, b, product);
  input [3:0] a, b;
  output [7:0] product;
  wire [3:0] a, b;
  wire [7:0] product;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_54, n_55, n_57, n_58, n_60;
  wire n_61;
  assign product[7] = 1'b0;
  NAND2XL g1033(.A (n_48), .B (n_61), .Y (product[6]));
  CLKXOR2X1 g1034(.A (n_44), .B (n_60), .Y (product[5]));
  AOI21XL g1035(.A0 (n_45), .A1 (n_57), .B0 (n_20), .Y (n_61));
  NOR2BXL g1036(.AN (n_48), .B (n_57), .Y (n_60));
  OAI21XL g1037(.A0 (n_55), .A1 (n_50), .B0 (n_58), .Y (product[4]));
  NAND2XL g1038(.A (n_50), .B (n_55), .Y (n_58));
  NOR2XL g1039(.A (n_47), .B (n_55), .Y (n_57));
  CLKINVX1 g1040(.A (n_54), .Y (product[3]));
  ADDFX1 g1041(.A (n_51), .B (n_31), .CI (n_49), .CO (n_55), .S (n_54));
  CLKINVX1 g1042(.A (n_52), .Y (product[2]));
  ADDFX1 g1043(.A (n_37), .B (n_13), .CI (n_41), .CO (n_51), .S (n_52));
  NOR2BXL g1044(.AN (n_48), .B (n_47), .Y (n_50));
  XNOR2X1 g1045(.A (n_12), .B (n_40), .Y (n_49));
  NAND2XL g1046(.A (n_42), .B (n_43), .Y (n_48));
  NOR2XL g1047(.A (n_42), .B (n_43), .Y (n_47));
  OAI31XL g1048(.A0 (n_33), .A1 (n_18), .A2 (n_34), .B0 (n_39), .Y
       (product[1]));
  CLKINVX1 g1049(.A (n_44), .Y (n_45));
  AOI211XL g1050(.A0 (n_27), .A1 (n_28), .B0 (n_24), .C0 (n_35), .Y
       (n_44));
  XOR2X1 g1051(.A (n_36), .B (n_28), .Y (n_43));
  NAND2BXL g1052(.AN (n_20), .B (n_38), .Y (n_42));
  AOI21XL g1053(.A0 (n_18), .A1 (n_32), .B0 (n_34), .Y (n_41));
  OAI21XL g1054(.A0 (n_30), .A1 (n_18), .B0 (n_39), .Y (n_40));
  NAND2XL g1055(.A (n_18), .B (n_30), .Y (n_39));
  OAI21XL g1056(.A0 (n_18), .A1 (n_12), .B0 (n_29), .Y (n_38));
  XNOR2X1 g1057(.A (n_14), .B (n_25), .Y (n_37));
  ADDHXL g1058(.A (n_23), .B (n_22), .CO (n_35), .S (n_36));
  NOR2XL g1059(.A (n_4), .B (n_26), .Y (n_34));
  CLKINVX1 g1060(.A (n_32), .Y (n_33));
  NAND2XL g1061(.A (n_4), .B (n_26), .Y (n_32));
  OR2X1 g1062(.A (n_14), .B (n_25), .Y (n_31));
  CLKINVX1 g1063(.A (n_29), .Y (n_30));
  ADDHXL g1064(.A (n_21), .B (n_19), .CO (n_28), .S (n_29));
  OR2X1 g1065(.A (n_22), .B (n_23), .Y (n_27));
  ADDFX1 g1066(.A (n_6), .B (n_9), .CI (n_5), .CO (n_25), .S (n_26));
  AOI21XL g1067(.A0 (n_16), .A1 (n_15), .B0 (n_20), .Y (n_24));
  AND3XL g1068(.A (b[3]), .B (a[1]), .C (n_16), .Y (n_23));
  AND3XL g1069(.A (b[1]), .B (a[3]), .C (n_15), .Y (n_22));
  NOR2BXL g1070(.AN (n_15), .B (n_11), .Y (n_21));
  NOR2XL g1071(.A (n_16), .B (n_15), .Y (n_20));
  NOR2BXL g1072(.AN (n_16), .B (n_10), .Y (n_19));
  ADDHXL g1073(.A (n_2), .B (n_3), .CO (n_18), .S (product[0]));
  NAND3BXL g1074(.AN (n_1), .B (a[1]), .C (b[3]), .Y (n_16));
  NAND3BXL g1075(.AN (n_0), .B (b[1]), .C (a[3]), .Y (n_15));
  XNOR2X1 g1076(.A (n_0), .B (n_1), .Y (n_14));
  XNOR2X1 g1077(.A (n_8), .B (n_7), .Y (n_13));
  NOR2XL g1078(.A (n_7), .B (n_8), .Y (n_12));
  AOI22XL g1079(.A0 (a[2]), .A1 (b[1]), .B0 (a[3]), .B1 (b[0]), .Y
       (n_11));
  AOI22XL g1080(.A0 (a[0]), .A1 (b[3]), .B0 (a[1]), .B1 (b[2]), .Y
       (n_10));
  NAND2XL g1081(.A (b[0]), .B (a[1]), .Y (n_9));
  NAND2XL g1082(.A (b[3]), .B (a[3]), .Y (n_8));
  NAND2XL g1083(.A (b[1]), .B (a[1]), .Y (n_7));
  NAND2XL g1084(.A (b[1]), .B (a[0]), .Y (n_6));
  NAND2XL g1085(.A (b[3]), .B (a[2]), .Y (n_5));
  NAND2XL g1086(.A (b[2]), .B (a[3]), .Y (n_4));
  AND2X1 g1087(.A (b[2]), .B (a[2]), .Y (n_3));
  AND2X1 g1088(.A (b[0]), .B (a[0]), .Y (n_2));
  NAND2XL g1089(.A (a[0]), .B (b[2]), .Y (n_1));
  NAND2XL g1090(.A (b[0]), .B (a[2]), .Y (n_0));
endmodule

module vedic4_4_2(a, b, product);
  input [3:0] a, b;
  output [7:0] product;
  wire [3:0] a, b;
  wire [7:0] product;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_54, n_55, n_57, n_58, n_60;
  wire n_61;
  assign product[7] = 1'b0;
  NAND2XL g1033(.A (n_48), .B (n_61), .Y (product[6]));
  CLKXOR2X1 g1034(.A (n_44), .B (n_60), .Y (product[5]));
  AOI21XL g1035(.A0 (n_45), .A1 (n_57), .B0 (n_20), .Y (n_61));
  NOR2BXL g1036(.AN (n_48), .B (n_57), .Y (n_60));
  OAI21XL g1037(.A0 (n_55), .A1 (n_50), .B0 (n_58), .Y (product[4]));
  NAND2XL g1038(.A (n_50), .B (n_55), .Y (n_58));
  NOR2XL g1039(.A (n_47), .B (n_55), .Y (n_57));
  CLKINVX1 g1040(.A (n_54), .Y (product[3]));
  ADDFX1 g1041(.A (n_51), .B (n_31), .CI (n_49), .CO (n_55), .S (n_54));
  CLKINVX1 g1042(.A (n_52), .Y (product[2]));
  ADDFX1 g1043(.A (n_37), .B (n_13), .CI (n_41), .CO (n_51), .S (n_52));
  NOR2BXL g1044(.AN (n_48), .B (n_47), .Y (n_50));
  XNOR2X1 g1045(.A (n_12), .B (n_40), .Y (n_49));
  NAND2XL g1046(.A (n_42), .B (n_43), .Y (n_48));
  NOR2XL g1047(.A (n_42), .B (n_43), .Y (n_47));
  OAI31XL g1048(.A0 (n_33), .A1 (n_18), .A2 (n_34), .B0 (n_39), .Y
       (product[1]));
  CLKINVX1 g1049(.A (n_44), .Y (n_45));
  AOI211XL g1050(.A0 (n_27), .A1 (n_28), .B0 (n_24), .C0 (n_35), .Y
       (n_44));
  XOR2X1 g1051(.A (n_36), .B (n_28), .Y (n_43));
  NAND2BXL g1052(.AN (n_20), .B (n_38), .Y (n_42));
  AOI21XL g1053(.A0 (n_18), .A1 (n_32), .B0 (n_34), .Y (n_41));
  OAI21XL g1054(.A0 (n_30), .A1 (n_18), .B0 (n_39), .Y (n_40));
  NAND2XL g1055(.A (n_18), .B (n_30), .Y (n_39));
  OAI21XL g1056(.A0 (n_18), .A1 (n_12), .B0 (n_29), .Y (n_38));
  XNOR2X1 g1057(.A (n_14), .B (n_25), .Y (n_37));
  ADDHXL g1058(.A (n_23), .B (n_22), .CO (n_35), .S (n_36));
  NOR2XL g1059(.A (n_4), .B (n_26), .Y (n_34));
  CLKINVX1 g1060(.A (n_32), .Y (n_33));
  NAND2XL g1061(.A (n_4), .B (n_26), .Y (n_32));
  OR2X1 g1062(.A (n_14), .B (n_25), .Y (n_31));
  CLKINVX1 g1063(.A (n_29), .Y (n_30));
  ADDHXL g1064(.A (n_21), .B (n_19), .CO (n_28), .S (n_29));
  OR2X1 g1065(.A (n_22), .B (n_23), .Y (n_27));
  ADDFX1 g1066(.A (n_6), .B (n_9), .CI (n_5), .CO (n_25), .S (n_26));
  AOI21XL g1067(.A0 (n_16), .A1 (n_15), .B0 (n_20), .Y (n_24));
  AND3XL g1068(.A (b[3]), .B (a[1]), .C (n_16), .Y (n_23));
  AND3XL g1069(.A (b[1]), .B (a[3]), .C (n_15), .Y (n_22));
  NOR2BXL g1070(.AN (n_15), .B (n_11), .Y (n_21));
  NOR2XL g1071(.A (n_16), .B (n_15), .Y (n_20));
  NOR2BXL g1072(.AN (n_16), .B (n_10), .Y (n_19));
  ADDHXL g1073(.A (n_2), .B (n_3), .CO (n_18), .S (product[0]));
  NAND3BXL g1074(.AN (n_1), .B (a[1]), .C (b[3]), .Y (n_16));
  NAND3BXL g1075(.AN (n_0), .B (b[1]), .C (a[3]), .Y (n_15));
  XNOR2X1 g1076(.A (n_0), .B (n_1), .Y (n_14));
  XNOR2X1 g1077(.A (n_8), .B (n_7), .Y (n_13));
  NOR2XL g1078(.A (n_7), .B (n_8), .Y (n_12));
  AOI22XL g1079(.A0 (a[2]), .A1 (b[1]), .B0 (a[3]), .B1 (b[0]), .Y
       (n_11));
  AOI22XL g1080(.A0 (a[0]), .A1 (b[3]), .B0 (a[1]), .B1 (b[2]), .Y
       (n_10));
  NAND2XL g1081(.A (b[0]), .B (a[1]), .Y (n_9));
  NAND2XL g1082(.A (b[3]), .B (a[3]), .Y (n_8));
  NAND2XL g1083(.A (b[1]), .B (a[1]), .Y (n_7));
  NAND2XL g1084(.A (b[1]), .B (a[0]), .Y (n_6));
  NAND2XL g1085(.A (b[3]), .B (a[2]), .Y (n_5));
  NAND2XL g1086(.A (b[2]), .B (a[3]), .Y (n_4));
  AND2X1 g1087(.A (b[2]), .B (a[2]), .Y (n_3));
  AND2X1 g1088(.A (b[0]), .B (a[0]), .Y (n_2));
  NAND2XL g1089(.A (a[0]), .B (b[2]), .Y (n_1));
  NAND2XL g1090(.A (b[0]), .B (a[2]), .Y (n_0));
endmodule

module vedic4_4_3(a, b, product);
  input [3:0] a, b;
  output [7:0] product;
  wire [3:0] a, b;
  wire [7:0] product;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_54, n_55, n_57, n_58, n_60;
  wire n_61;
  assign product[7] = 1'b0;
  NAND2XL g1033(.A (n_48), .B (n_61), .Y (product[6]));
  CLKXOR2X1 g1034(.A (n_44), .B (n_60), .Y (product[5]));
  AOI21XL g1035(.A0 (n_45), .A1 (n_57), .B0 (n_20), .Y (n_61));
  NOR2BXL g1036(.AN (n_48), .B (n_57), .Y (n_60));
  OAI21XL g1037(.A0 (n_55), .A1 (n_50), .B0 (n_58), .Y (product[4]));
  NAND2XL g1038(.A (n_50), .B (n_55), .Y (n_58));
  NOR2XL g1039(.A (n_47), .B (n_55), .Y (n_57));
  CLKINVX1 g1040(.A (n_54), .Y (product[3]));
  ADDFX1 g1041(.A (n_51), .B (n_31), .CI (n_49), .CO (n_55), .S (n_54));
  CLKINVX1 g1042(.A (n_52), .Y (product[2]));
  ADDFX1 g1043(.A (n_37), .B (n_13), .CI (n_41), .CO (n_51), .S (n_52));
  NOR2BXL g1044(.AN (n_48), .B (n_47), .Y (n_50));
  XNOR2X1 g1045(.A (n_12), .B (n_40), .Y (n_49));
  NAND2XL g1046(.A (n_42), .B (n_43), .Y (n_48));
  NOR2XL g1047(.A (n_42), .B (n_43), .Y (n_47));
  OAI31XL g1048(.A0 (n_33), .A1 (n_18), .A2 (n_34), .B0 (n_39), .Y
       (product[1]));
  CLKINVX1 g1049(.A (n_44), .Y (n_45));
  AOI211XL g1050(.A0 (n_27), .A1 (n_28), .B0 (n_24), .C0 (n_35), .Y
       (n_44));
  XOR2X1 g1051(.A (n_36), .B (n_28), .Y (n_43));
  NAND2BXL g1052(.AN (n_20), .B (n_38), .Y (n_42));
  AOI21XL g1053(.A0 (n_18), .A1 (n_32), .B0 (n_34), .Y (n_41));
  OAI21XL g1054(.A0 (n_30), .A1 (n_18), .B0 (n_39), .Y (n_40));
  NAND2XL g1055(.A (n_18), .B (n_30), .Y (n_39));
  OAI21XL g1056(.A0 (n_18), .A1 (n_12), .B0 (n_29), .Y (n_38));
  XNOR2X1 g1057(.A (n_14), .B (n_25), .Y (n_37));
  ADDHXL g1058(.A (n_23), .B (n_22), .CO (n_35), .S (n_36));
  NOR2XL g1059(.A (n_4), .B (n_26), .Y (n_34));
  CLKINVX1 g1060(.A (n_32), .Y (n_33));
  NAND2XL g1061(.A (n_4), .B (n_26), .Y (n_32));
  OR2X1 g1062(.A (n_14), .B (n_25), .Y (n_31));
  CLKINVX1 g1063(.A (n_29), .Y (n_30));
  ADDHXL g1064(.A (n_21), .B (n_19), .CO (n_28), .S (n_29));
  OR2X1 g1065(.A (n_22), .B (n_23), .Y (n_27));
  ADDFX1 g1066(.A (n_6), .B (n_9), .CI (n_5), .CO (n_25), .S (n_26));
  AOI21XL g1067(.A0 (n_16), .A1 (n_15), .B0 (n_20), .Y (n_24));
  AND3XL g1068(.A (b[3]), .B (a[1]), .C (n_16), .Y (n_23));
  AND3XL g1069(.A (b[1]), .B (a[3]), .C (n_15), .Y (n_22));
  NOR2BXL g1070(.AN (n_15), .B (n_11), .Y (n_21));
  NOR2XL g1071(.A (n_16), .B (n_15), .Y (n_20));
  NOR2BXL g1072(.AN (n_16), .B (n_10), .Y (n_19));
  ADDHXL g1073(.A (n_2), .B (n_3), .CO (n_18), .S (product[0]));
  NAND3BXL g1074(.AN (n_1), .B (a[1]), .C (b[3]), .Y (n_16));
  NAND3BXL g1075(.AN (n_0), .B (b[1]), .C (a[3]), .Y (n_15));
  XNOR2X1 g1076(.A (n_0), .B (n_1), .Y (n_14));
  XNOR2X1 g1077(.A (n_8), .B (n_7), .Y (n_13));
  NOR2XL g1078(.A (n_7), .B (n_8), .Y (n_12));
  AOI22XL g1079(.A0 (a[2]), .A1 (b[1]), .B0 (a[3]), .B1 (b[0]), .Y
       (n_11));
  AOI22XL g1080(.A0 (a[0]), .A1 (b[3]), .B0 (a[1]), .B1 (b[2]), .Y
       (n_10));
  NAND2XL g1081(.A (b[0]), .B (a[1]), .Y (n_9));
  NAND2XL g1082(.A (b[3]), .B (a[3]), .Y (n_8));
  NAND2XL g1083(.A (b[1]), .B (a[1]), .Y (n_7));
  NAND2XL g1084(.A (b[1]), .B (a[0]), .Y (n_6));
  NAND2XL g1085(.A (b[3]), .B (a[2]), .Y (n_5));
  NAND2XL g1086(.A (b[2]), .B (a[3]), .Y (n_4));
  AND2X1 g1087(.A (b[2]), .B (a[2]), .Y (n_3));
  AND2X1 g1088(.A (b[0]), .B (a[0]), .Y (n_2));
  NAND2XL g1089(.A (a[0]), .B (b[2]), .Y (n_1));
  NAND2XL g1090(.A (b[0]), .B (a[2]), .Y (n_0));
endmodule

module vedic8_8(a, b, product);
  input [7:0] a, b;
  output [15:0] product;
  wire [7:0] a, b;
  wire [15:0] product;
  wire [7:0] p1;
  wire [7:0] p2;
  wire [7:0] p3;
  wire [15:0] temp1;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, carry, overflow,
       sum;
  assign product[0] = 1'b0;
  assign product[1] = 1'b0;
  assign product[2] = 1'b0;
  assign product[3] = 1'b0;
  assign product[4] = 1'b0;
  assign product[5] = 1'b0;
  assign product[6] = 1'b0;
  assign product[7] = 1'b0;
  assign product[8] = 1'b0;
  assign product[9] = 1'b0;
  assign product[10] = 1'b0;
  assign product[11] = 1'b0;
  assign product[12] = 1'b0;
  assign product[13] = 1'b0;
  assign product[14] = 1'b0;
  compressor6_3 c1(1'b0, p1[3], p2[3], 1'b0, p1[4], p2[4], sum, carry,
       overflow);
  csa_tree_add_83_52_group_59 csa_tree_add_83_52_groupi(.in_0
       ({overflow, carry, sum}), .in_1 ({1'b0, p3[6:0], 8'b00000000}),
       .in_2 ({5'b00000, p2[6:0], 4'b0000}), .in_3 ({1'b0,
       temp1[6:0]}), .in_4 ({5'b00000, p1[6:0], 4'b0000}), .out_0
       ({product[15], UNCONNECTED, UNCONNECTED0, UNCONNECTED1,
       UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9,
       UNCONNECTED10, UNCONNECTED11, UNCONNECTED12, UNCONNECTED13}));
  vedic4_4 vm1(a[3:0], b[3:0], {UNCONNECTED14, temp1[6:0]});
  vedic4_4_1 vm2(a[3:0], b[7:4], {UNCONNECTED15, p1[6:0]});
  vedic4_4_2 vm3(a[7:4], b[3:0], {UNCONNECTED16, p2[6:0]});
  vedic4_4_3 vm4(a[7:4], b[7:4], {UNCONNECTED17, p3[6:0]});
endmodule

module hybrid_mac(activation, weight, clk, reset, mac_result);
  input [7:0] activation, weight;
  input clk, reset;
  output [31:0] mac_result;
  wire [7:0] activation, weight;
  wire clk, reset;
  wire [31:0] mac_result;
  wire [31:0] reduction_result;
  wire [15:0] product;
  wire UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25;
  wire UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, UNCONNECTED29,
       UNCONNECTED30, UNCONNECTED31, UNCONNECTED32, UNCONNECTED33;
  wire UNCONNECTED34, UNCONNECTED35, UNCONNECTED36, UNCONNECTED37,
       UNCONNECTED38, UNCONNECTED39, UNCONNECTED40;
  accumulator acc(.clk (clk), .reset (reset), .input_data
       ({reduction_result[31:8], 7'b0000000, product[15]}),
       .accumulated_result (mac_result));
  reduction_unit_with_6_3 hreduce(.A (16'b0000000000000000), .B
       (16'b0000000000000000), .C (16'b0000000000000000), .D
       (16'b0000000000000000), .E (16'b0000000000000000), .F
       (16'b0000000000000000), .G (16'b0000000000000000), .H
       (16'b0000000000000000), .Result ({reduction_result[31:8],
       UNCONNECTED18, UNCONNECTED19, UNCONNECTED20, UNCONNECTED21,
       UNCONNECTED22, UNCONNECTED23, UNCONNECTED24, UNCONNECTED25}));
  vedic8_8 vedic_mult(.a (activation), .b (weight), .product
       ({product[15], UNCONNECTED26, UNCONNECTED27, UNCONNECTED28,
       UNCONNECTED29, UNCONNECTED30, UNCONNECTED31, UNCONNECTED32,
       UNCONNECTED33, UNCONNECTED34, UNCONNECTED35, UNCONNECTED36,
       UNCONNECTED37, UNCONNECTED38, UNCONNECTED39, UNCONNECTED40}));
endmodule

